// Generated by `npm run version:sync` from release/version.json and release/feature-flags.json. Do not edit.
export const RELEASE_METADATA = Object.freeze({
  schemaVersion: 1,
  product: "openbexi-earth-orbit",
  version: "2.1.0",
  baselineRuntimeVersion: "1.7.6",
  channel: "development",
  publicationState: "development",
  maturity: "experimental",
  safetyClass: "non-operational",
  candidateAt: null,
  releasedAt: null,
  runtimeVersionMigration: "complete"
});

export const APP_VERSION = RELEASE_METADATA.version;
export const RELEASE_DATE = RELEASE_METADATA.releasedAt ?? RELEASE_METADATA.candidateAt;

export const RELEASE_FEATURE_FLAGS = Object.freeze({
  "experimental_conjunction_screening": Object.freeze({"enabled":true,"scope":"browser","scientificMaturity":"Experimental","safetyClass":"non-operational"})
});
export const EXPERIMENTAL_CONJUNCTION_SCREENING_ENABLED =
  RELEASE_FEATURE_FLAGS.experimental_conjunction_screening?.enabled === true;
