import assert from 'assert';
import fs from 'fs';
import { satelliteMenuLoader } from '../js/SatelliteMenuLoader.js';

function indexOfOrFail(text, needle, message) {
  const index = text.indexOf(needle);
  assert(index >= 0, message);
  return index;
}

function run() {
  const html = satelliteMenuLoader();
  const css = fs.readFileSync('css/style.css', 'utf8');
  const indexHtml = fs.readFileSync('index.html', 'utf8');
  const markdownViewerHtml = fs.readFileSync('markdown_viewer.html', 'utf8');
  const swaggerHtml = fs.readFileSync('swagger.html', 'utf8');
  const launchTimeline = fs.readFileSync('js/ganttTimelineLoader.js', 'utf8');
  const reentryTimeline = fs.readFileSync('js/reentryTimeline.js', 'utf8');
  const marsFrameLoader = fs.readFileSync('js/MarsFrameLoader.js', 'utf8');
  const mercatorMapLoader = fs.readFileSync('js/mercatorMapLoader.js', 'utf8');

  assert(!html.includes('role="tablist"'), 'main menu no longer exposes a tablist');
  assert(!html.includes('role="tab"'), 'main menu no longer exposes tab buttons');
  assert(!html.includes('role="tabpanel"'), 'main menu no longer exposes tab panels');
  assert(!html.includes('data-tab-target'), 'main menu no longer uses tab target wiring');
  assert(!html.includes('menu-tab-rail'), 'vertical tab rail markup is removed');
  assert(!css.includes('.menu-tab-rail'), 'vertical tab rail CSS is removed');
  assert(!indexHtml.includes('MENU_TAB_STORAGE_KEY'), 'selected tab persistence is removed');
  assert(!indexHtml.includes('activateMenuTabById'), 'tab activation logic is removed');

  assert(html.includes('class="menu-accordion"'), 'menu uses stacked accordion markup');
  assert(html.includes('menu-accordion-heading'), 'accordion headers are present');
  assert(html.includes('role="button"'), 'accordion headers expose button semantics');
  assert(!html.includes('aria-controls="filtersContent"'), 'standalone Filters accordion target is removed');
  assert(html.includes('aria-controls="satelliteSelectionContent"'), 'Satellite header controls its content');
  assert(html.includes('aria-expanded="true" data-collapsible-target="viewContent"'), 'Views & Time starts expanded in markup');
  assert(html.includes('aria-expanded="true" data-collapsible-target="satelliteSelectionContent"'), 'Satellite Selection starts expanded in markup');
  assert(!html.includes('data-collapsible-target="filtersContent"'), 'Filters no longer has its own accordion state');
  assert(html.includes('data-default-expanded="true"'), 'default-expanded accordion state is declared');
  assert(html.includes('data-default-collapsed="true"'), 'default-collapsed accordion state is declared for non-default sections');

  assert(!html.includes('id="filtersAccordionSection"'), 'standalone filters accordion is removed');
  assert(!html.includes('id="filtersAccordionHeader"'), 'standalone filters header is removed');
  assert(!html.includes('id="filtersContent"'), 'standalone filters content panel is removed');
  assert(!html.includes('Filters - Satellites Found'), 'old Filters - Satellites Found heading is removed');
  const satelliteSection = indexOfOrFail(html, 'id="satelliteAccordionSection"', 'satellite accordion exists');
  const viewSection = indexOfOrFail(html, 'id="viewAccordionSection"', 'view accordion exists');
  const timelinesSection = indexOfOrFail(html, 'id="timelinesAccordionSection"', 'timelines accordion exists');
  const shareSection = indexOfOrFail(html, 'id="shareAccordionSection"', 'share accordion exists');
  const helpSection = indexOfOrFail(html, 'id="helpAccordionSection"', 'help accordion exists');
  assert(!html.includes('id="otherAccordionSection"'), 'Other Selections accordion section is removed');
  assert(!html.includes('id="otherSelectionsContent"'), 'Other Selections content panel is removed');
  assert(!html.includes('id="otherSelection"'), 'Other Selections dropdown is removed');
  assert(!html.includes('id="settingsAccordionSection"'), 'Settings accordion section is removed');
  assert(!html.includes('data-collapsible-target="settingsContent"'), 'Settings content target is removed');
  assert(
    viewSection < satelliteSection && satelliteSection < timelinesSection &&
      timelinesSection < shareSection && shareSection < helpSection,
    'accordion section order is Views & Time, Satellite Selection, Timelines, Share, Help'
  );
  assert(html.includes('Views &amp; Time'), 'View section is renamed to Views & Time');

  const viewContent = indexOfOrFail(html, 'id="viewContent"', 'View content exists');
  const solarSystemToggle = indexOfOrFail(html, 'id="solarSystemOverviewToggle"', 'Solar System toggle exists');
  const starsMilkyWayToggle = indexOfOrFail(html, 'id="starsMilkyWayToggle"', 'Stars & Milky Way toggle exists');
  const globeToggle = indexOfOrFail(html, 'id="view3DToggle"', 'Globe toggle exists');
  const highDefToggle = indexOfOrFail(html, 'id="highDefToggle"', 'High Def toggle exists');
  const axesToggle = indexOfOrFail(html, 'id="showECEFAxesToggle"', 'ECEF Axes toggle exists');
  const mercatorToggle = indexOfOrFail(html, 'id="viewMercatorToggle"', 'Mercator toggle exists');
  const dayNightToggle = indexOfOrFail(html, 'id="showDayNightToggle"', 'Day/Night toggle exists');
  const solarOptions = indexOfOrFail(html, 'id="solarSystemOptions"', 'Solar System options container exists');
  const starOptions = indexOfOrFail(html, 'id="starsMilkyWayOptions"', 'Stars & Milky Way options container exists');
  const raDecGridToggle = indexOfOrFail(html, 'id="showRaDecGridToggle"', 'RA/Dec Grid toggle exists');
  const brightStarLabelsToggle = indexOfOrFail(html, 'id="showBrightStarLabelsToggle"', 'Bright Labels toggle exists');
  const starAtmosphereToggle = indexOfOrFail(html, 'id="showStarAtmosphereToggle"', 'Atmosphere toggle exists');
  const starCatalogSummary = indexOfOrFail(html, 'id="starCatalogSummary"', 'bundled star catalog summary exists');
  assert(
    viewContent < solarSystemToggle && solarSystemToggle < starsMilkyWayToggle && starsMilkyWayToggle < globeToggle &&
      globeToggle < highDefToggle && highDefToggle < axesToggle && axesToggle < mercatorToggle &&
      mercatorToggle < dayNightToggle && dayNightToggle < solarOptions && solarOptions < starOptions && starOptions < raDecGridToggle &&
      raDecGridToggle < brightStarLabelsToggle && brightStarLabelsToggle < starAtmosphereToggle &&
      starAtmosphereToggle < starCatalogSummary,
    'Views & Time menu order is Solar/Stars, Globe/HighDef/ECEF, Mercator/Day-Night, then mode sub-controls'
  );
  assert(!html.includes('Use the time slider at the top of the screen to control simulation speed.'), 'old Views & Time slider guidance is removed');
  assert(!html.includes('menu-time-warp-control'), 'Views & Time menu Time x slider is removed');
  assert(!html.includes('menuTimeWarpSlider'), 'menu Time x slider id is removed');
  assert(!html.includes('menuTimeWarpVal'), 'menu Time x value is removed');
  assert(html.includes('class="view-checkbox-table"'), 'View menu uses a 3x3 checkbox table for alignment');
  assert(html.includes('aria-label="Views and time display controls"'), 'View checkbox table has an accessible group name');
  assert((html.match(/class="view-checkbox-cell"/g) || []).length === 7, 'View checkbox table has seven visible checkbox cells');
  assert((html.match(/class="view-checkbox-cell view-checkbox-empty"/g) || []).length === 2, 'View checkbox table has two empty cells to preserve the 3x3 layout');
  assert(html.includes('<label><input type="checkbox" id="solarSystemOverviewToggle">Solar System</label>'), 'Solar System is unchecked by default');
  assert(html.includes('<label><input type="checkbox" id="starsMilkyWayToggle" checked>Stars &amp; Milky Way</label>'), 'Stars & Milky Way is checked by default');
  assert(html.includes('<label><input type="checkbox" id="view3DToggle" checked>Globe</label>'), 'Globe remains checked by default');
  assert(html.includes('<label><input type="checkbox" id="highDefToggle"> High Def.</label>'), 'High Def remains unchecked by default');
  assert(html.includes('<label><input type="checkbox" id="showECEFAxesToggle"> ECEF Axes</label>'), 'ECEF Axes remains unchecked by default');
  assert(html.includes('<label><input type="checkbox" id="viewMercatorToggle">Mercator</label>'), 'Mercator remains unchecked by default');
  assert(html.includes('<label><input type="checkbox" id="showDayNightToggle" checked> Day/Night</label>'), 'Day/Night remains checked by default');
  assert(html.includes('id="solarSystemOptions" class="solar-system-options" hidden aria-hidden="true"'), 'Solar System sub-controls are hidden by default');
  assert(html.includes('id="solarSystemPlanetLabelsToggle" checked'), 'Solar System planet labels are enabled by default inside mode');
  assert(html.includes('id="solarSystemOrbitPathsToggle" checked'), 'Solar System orbit paths are enabled by default inside mode');
  assert(html.includes('id="solarSystemPlanetTexturesToggle" checked'), 'Solar System planet textures are enabled by default inside mode');
  assert(html.includes('id="solarSystemSunGlowToggle" checked'), 'Solar System sun glow is enabled by default inside mode');
  assert(html.includes('solarSystemBackButton'), 'Solar System has a back-to-overview action');
  assert(html.includes('solarSystemExitButton'), 'Solar System has an exit action');
  assert(html.includes('id="starsMilkyWayOptions" class="stars-milky-way-options" aria-hidden="false"'), 'Stars & Milky Way sub-controls are visible by default');
  assert(html.includes('<label><input type="checkbox" id="showRaDecGridToggle">RA/Dec Grid</label>'), 'RA/Dec Grid is unchecked by default');
  assert(html.includes('<label><input type="checkbox" id="showBrightStarLabelsToggle">Bright Labels</label>'), 'Bright Labels is unchecked by default');
  assert(html.includes('<label><input type="checkbox" id="showStarAtmosphereToggle">Atmosphere</label>'), 'Atmosphere is unchecked by default');
  assert(html.includes('id="starCatalogSummary" class="star-catalog-summary" aria-live="polite" hidden aria-hidden="true"'), 'bundled catalog summary is hidden by default');
  assert(!html.includes('starMagnitudeLimitSlider'), 'main menu no longer exposes a Magnitude limit slider');
  assert(!html.includes('starMagnitudeLimitValue'), 'main menu no longer exposes a Magnitude limit value');
  assert(html.includes('view-control-row view-control-row-three'), 'View sub-option rows keep three-column CSS');
  assert(!html.includes('view-control-row view-shortcut-row'), 'View menu no longer has a satellite shortcut row');
  assert(html.includes('class="satellite-shortcut-row"'), 'Satellite Selection has a shortcut button row');
  assert(html.includes('aria-label="Starlink shortcut unavailable"'), 'Starlink shortcut has unavailable accessible text before TLE load');
  assert(html.includes('aria-label="ISS shortcut unavailable"'), 'ISS shortcut has unavailable accessible text before TLE load');
  assert(html.includes('Starlink unavailable'), 'Starlink shortcut has required unavailable fallback text');
  assert(html.includes('ISS unavailable'), 'ISS shortcut has required unavailable fallback text');

  assert(indexHtml.includes('DEFAULT_EXPANDED_ACCORDION_SECTIONS = new Set(['), 'required accordion sections are forced open on page load');
  assert(indexHtml.includes('DEFAULT_COLLAPSED_ACCORDION_SECTIONS'), 'other accordion defaults are explicit');
  ['viewContent', 'satelliteSelectionContent'].forEach(id => {
    assert(indexHtml.includes(`'${id}'`), `${id} starts expanded on launch`);
  });
  assert(!indexHtml.includes("'filtersContent'"), 'removed Filters content is not part of accordion defaults');
  ['timelineContent', 'shareContent', 'helpContent'].forEach(id => {
    assert(indexHtml.includes(`'${id}'`), `${id} starts collapsed on launch`);
  });
  assert(!indexHtml.includes("'otherSelectionsContent'"), 'removed Other Selections content is not part of accordion defaults');
  assert(!indexHtml.includes("'settingsContent'"), 'settings content is not part of accordion defaults');
  assert(indexHtml.includes('persisted state cannot reopen') || indexHtml.includes('persisted state cannot override'), 'persisted accordion state cannot override launch defaults');
  assert(indexHtml.includes('setAccordionSectionCollapsed(targetId, nextCollapsed, collapsedSections)'), 'accordion toggles only the targeted section');
  assert(indexHtml.includes('Multiple sections may remain open'), 'implementation documents multi-open accordion behavior');
  assert(indexHtml.includes("expandCollapsibleSection('satelliteSelectionContent')"), 'YPR-enabled selection opens Satellite Selection');
  assert(!indexHtml.includes("expandCollapsibleSection('filtersContent')"), 'YPR selection does not force unrelated sections open');

  assert(!/>\s*Active\s*</i.test(html), 'filter menu does not expose an Active control');
  assert(indexHtml.includes('EXCLUDED_COMPANY_FILTER_OPTIONS'), 'index defines generated company/tag exclusions');
  assert(indexHtml.includes("new Set(['ACTIVE'])"), 'Active is excluded from generated company/tag chips');
  assert(html.includes('id="satelliteSearchInput"'), 'satellite search input is present');
  assert(!html.includes('Select Satellite:'), 'old Select Satellite visible label is removed');
  assert(!html.includes('Search by name, NORAD ID, orbit type, or tag.'), 'old satellite selection helper text is removed');
  assert(html.includes('aria-label="Search satellite by name, NORAD ID, orbit type, or tag"'), 'satellite search keeps an accessible name after visible label removal');
  assert(html.includes('role="combobox"'), 'satellite search uses combobox semantics');
  assert(html.includes('aria-expanded="false"'), 'satellite search exposes collapsed aria-expanded state');
  assert(html.includes('aria-controls="satelliteSearchResults"'), 'satellite search controls the result list');
  assert(html.includes('id="satelliteSearchResults"'), 'satellite search results list is present');
  assert(html.includes('role="listbox"'), 'satellite search results use listbox semantics');
  assert(html.includes('id="satelliteSearchClear"'), 'satellite search clear action is present');
  assert(html.includes('Satellites Selection - Found'), 'Satellite Selection heading includes found-count text');
  assert(html.includes('id="satelliteCountDisplay" class="satellite-found-count" aria-live="polite" aria-label="Satellites found: 0"'), 'found count is in the Satellite Selection heading with live accessible text');
  assert(html.includes('id="resetFiltersButton"'), 'reset filters action is present');
  assert(!html.includes('id="debrisFilter"'), 'old standalone debris filter group is removed');
  assert(!html.includes('data-debris-filter'), 'old debris filter buttons are removed');
  assert(!html.includes('Debris only'), 'old Debris only button is removed');
  assert(!html.includes('id="filterStatusSummary"'), 'active filter summary is removed');
  assert(!html.includes('MEO + All tags + Debris shown'), 'old filter summary text is removed');
  assert(html.includes('id="filterEmptyState"'), 'filter empty state is present');
  assert(!html.includes('Orbit filter (multi-select):'), 'old orbit filter visible label is removed');
  assert(!html.includes('Choose one or more orbit families. ALL enables every orbit category.'), 'old orbit filter helper text is removed');
  assert(!html.includes('Tag filter (multi-select):'), 'old tag filter visible label is removed');
  assert(!html.includes('Use tags to narrow by constellation, operator, or mission group.'), 'old tag filter helper text is removed');
  assert(!html.includes('Debris filter:'), 'old debris filter visible label is removed');
  assert(!html.includes('Show all objects, hide debris, or inspect debris only.'), 'old debris helper text is removed');
  assert(html.includes('id="orbitTypeFilter"'), 'orbit filter controls remain present');
  assert(html.includes('aria-label="Orbit filter"'), 'orbit filter keeps an accessible name');
  const orbitAllButton = indexOfOrFail(html, 'data-orbit-filter="ALL"', 'ALL orbit filter exists');
  const orbitGeoButton = indexOfOrFail(html, 'data-orbit-filter="GEO"', 'GEO orbit filter exists');
  const orbitMeoButton = indexOfOrFail(html, 'data-orbit-filter="MEO"', 'MEO orbit filter exists');
  const orbitLeoButton = indexOfOrFail(html, 'data-orbit-filter="LEO"', 'LEO orbit filter exists');
  const orbitHroButton = indexOfOrFail(html, '>HRO</button>', 'HRO orbit label exists');
  const orbitDebrisButton = indexOfOrFail(html, 'data-orbit-filter="DEBRIS"', 'Debris orbit/category filter exists');
  const orbitOthersButton = indexOfOrFail(html, '>Others</button>', 'Others orbit label exists');
  assert(
    orbitAllButton < orbitGeoButton && orbitGeoButton < orbitMeoButton && orbitMeoButton < orbitLeoButton &&
      orbitLeoButton < orbitHroButton && orbitHroButton < orbitDebrisButton && orbitDebrisButton < orbitOthersButton,
    'orbit/category row order is ALL, GEO, MEO, LEO, HRO, Debris, Others'
  );
  assert(indexHtml.includes('const ORBIT_DEBRIS_OPTION = "DEBRIS"'), 'index defines Debris as a visible orbit/category option');
  assert(indexHtml.includes('return isDebrisSatellite(satData);'), 'Debris orbit/category option filters to debris candidates only');
  assert(indexHtml.includes('value !== ORBIT_DEBRIS_OPTION'), 'normal orbit clicks switch away from the exclusive Debris filter');
  assert(indexHtml.includes('function buildFilteredSatellitesBySelection()'), 'index has one canonical filtered satellite builder');
  assert(indexHtml.includes('const filteredTLEs = buildFilteredSatellitesBySelection();'), 'updateSatelliteList uses the canonical filtered satellite set');
  assert(indexHtml.includes("import { buildSatelliteSearchMatches } from './js/satelliteSearchUtils.js';"), 'index imports shared satellite search matching helper');
  assert(indexHtml.includes('renderSatelliteSearchResults(filteredTLEs, false)'), 'visible search results are rendered from the canonical filtered satellite set');
  assert(indexHtml.includes('filteredTLEs.forEach(s => {'), 'hidden legacy select options are built from the canonical filtered satellite set');
  assert(indexHtml.includes('renderSatelliteSearchResults(buildFilteredSatellitesBySelection(), true)'), 'user search interactions reopen results from active filters');
  assert(indexHtml.includes('setSatelliteFoundCountLabel(searchState.countLabel)'), 'visible search count is derived from the same search state as dropdown results');
  assert(indexHtml.includes('setSatelliteFoundCountLabel('), 'found count updates use one accessible helper');

  const satelliteSelection = indexOfOrFail(html, 'Satellites Selection - Found', 'satellite selection section exists');
  const searchInput = indexOfOrFail(html, 'id="satelliteSearchInput"', 'search input exists');
  const clearSearch = indexOfOrFail(html, 'id="satelliteSearchClear"', 'clear search exists');
  const resetFilters = indexOfOrFail(html, 'id="resetFiltersButton"', 'reset filters exists');
  const satelliteShortcutRow = indexOfOrFail(html, 'class="satellite-shortcut-row"', 'satellite shortcut row exists');
  const starlinkShortcut = indexOfOrFail(html, 'id="selectFirstStarlinkButton"', 'Starlink shortcut exists');
  const issShortcut = indexOfOrFail(html, 'id="selectIssButton"', 'ISS shortcut exists');
  const satelliteFilterPanel = indexOfOrFail(html, 'class="satellite-filter-panel filters-panel"', 'filter panel is inside Satellite Selection');
  const orbitFilter = indexOfOrFail(html, 'id="orbitTypeFilter"', 'orbit filter exists');
  const companyFilter = indexOfOrFail(html, 'id="companyFilter"', 'tag filter exists');
  const selectedControls = indexOfOrFail(html, 'id="selectedSatelliteControls"', 'selected satellite controls exist');
  const firstSatelliteCheckbox = indexOfOrFail(html, 'id="showYPRToggle"', 'satellite-specific checkboxes exist');
  assert(
    satelliteSelection < searchInput && searchInput < clearSearch && clearSearch < resetFilters &&
      resetFilters < satelliteShortcutRow && satelliteShortcutRow < starlinkShortcut &&
      starlinkShortcut < issShortcut && issShortcut < satelliteFilterPanel && satelliteFilterPanel < orbitFilter &&
      orbitFilter < companyFilter && companyFilter < selectedControls && selectedControls < firstSatelliteCheckbox,
    'search, Clear, Reset Filters, shortcuts, filters, and selected-satellite controls appear inside Satellite Selection in the required order'
  );
  assert(html.includes('id="selectedSatelliteControls" class="satellite-option-grid" aria-label="Selected satellite options" aria-hidden="true" hidden'), 'satellite-specific controls are hidden until selection');
  assert(html.includes('id="showFootprintCheckbox"><span>Show Footprint</span>'), 'Show Footprint checkbox exists and is unchecked by default');
  assert(html.includes('id="showOnlySelectedSatellite" checked'), 'Show only selected satellite checkbox is checked by default when shown');
  assert(html.includes('id="showOrbitFrameToggle"> Orbit Frame (LVLH)'), 'Orbit Frame checkbox exists and is unchecked by default');
  assert(html.includes('id="showOrbitToggle"> Show Orbit'), 'Show Orbit checkbox exists and is unchecked by default');
  assert(!html.includes('No satellite selected'), 'visible no-selection placeholder text is removed from generated menu');
  assert(!html.includes('id="satelliteInfo"'), 'Satellite Selection no longer contains the detailed metadata/TLE table');

  const timelinePanel = indexOfOrFail(html, 'id="timelineContent"', 'timeline content exists');
  const sharePanel = indexOfOrFail(html, 'id="shareContent"', 'share content exists');
  const helpPanel = indexOfOrFail(html, 'id="helpContent"', 'help content exists');
  assert(satelliteSection < timelinePanel && timelinePanel < sharePanel && sharePanel < helpPanel, 'Timelines/Share/Help retain order after Satellite Selection');
  assert(html.includes('type="checkbox" id="launchTimelineToggle"'), 'launch timeline toggle is a checkbox');
  assert(html.includes('type="checkbox" id="reentryTimelineToggle"'), 're-entry timeline toggle is a checkbox');
  assert(!html.includes('other-selections-heading'), 'removed Other Selections header has no special text-style class');
  assert(!html.includes('data-collapsible-target="otherSelectionsContent"'), 'removed Other Selections is not collapsible');
  assert(html.includes('data-collapsible-target="shareContent"'), 'Share section is collapsible');
  assert(html.includes('data-collapsible-target="helpContent"'), 'Help section is collapsible');
  assert(html.includes('id="menuHeaderRow"'), 'menu header row exists');
  assert(html.indexOf('id="versionDisplay"') < html.indexOf('id="serverStatusBlock"'), 'version appears before server status in header row');
  assert(html.includes('id="serverStatusButton"'), 'server status button exists');
  assert(html.includes('id="serverStatusIcon"'), 'server status uses an icon element');
  assert(html.includes('src="icons/server_checking.svg"'), 'server status starts with checking icon');
  assert(html.includes('aria-label="Checking server connection"'), 'server status has checking accessible text');
  assert(html.includes('id="serverStatusPanel"'), 'server status panel exists');
  assert(html.includes('id="serverReconnectButton"'), 'server status exposes reconnect action');
  assert(!html.includes('Server unavailable. Using local satellite data.'), 'launch offline banner is removed');
  assert(!html.includes('id="serverOfflineNotice"'), 'server offline notice hook is removed');
  assert(html.includes('id="copyShareLinkButton"'), 'Share section includes Copy Link');
  assert(html.includes('id="nativeShareButton"'), 'Share section includes native share action');
  assert(html.includes('id="shareLinkOutput"'), 'Share section includes generated link output');
  assert(html.includes('id="shareImagePreview"'), 'Share section includes canvas image preview');
  assert(html.includes('id="previewShareImageButton"'), 'Share section includes Preview Image action');
  assert(html.includes('id="downloadShareImageButton"'), 'Share section includes Download Image action');
  assert(html.includes('id="copyShareImageButton"'), 'Share section includes Copy Image action');
  assert(html.includes('href="https://github.com/arcazj/openbexi_earth_orbit"'), 'Help includes GitHub project link');
  assert(html.includes('target="_blank" rel="noopener noreferrer"'), 'GitHub Help link opens safely in a new tab');
  assert(html.includes('id="readmeMarkdownLink"'), 'Help includes README Markdown action');
  assert(html.includes('href="markdown_viewer.html?source=README.md&amp;title=README"'), 'README Markdown action opens the Markdown viewer');
  assert(html.includes('id="releasesHistoryMarkdownLink"'), 'Help includes Releases History Markdown action');
  assert(html.includes('href="markdown_viewer.html?source=PROMPT_History.md&amp;title=Releases%20History"'), 'Releases History action opens the Markdown viewer');
  assert(html.includes('>Releases History</strong>'), 'Prompt History action is renamed to Releases History');
  assert(!html.includes('>Prompt History</a>'), 'Prompt History is not the visible Help action text');
  assert(!html.includes('id="helpMarkdownPanel"'), 'Help no longer renders Markdown inline in the menu');
  assert(!html.includes('id="helpMarkdownContent"'), 'Help no longer has an inline Markdown content target');
  assert(html.includes('class="help-smart-grid"'), 'Help uses a smart document grid');
  assert(html.includes('id="licenseMarkdownLink"'), 'Help includes Licenses link hook');
  assert(html.includes('href="LICENSE.md"'), 'Help includes Markdown license link');
  assert(fs.existsSync('LICENSE.md'), 'LICENSE.md exists for the Help license link');
  assert(html.includes('>Licenses</strong>'), 'Help labels the license action as Licenses');
  assert(!html.includes('Swagger / API Documentation'), 'old Swagger/API heading is removed');
  assert(html.includes('Developer Docs'), 'Help includes developer documentation section');
  assert(html.includes('id="swaggerDocsLink"'), 'Help includes Swagger UI link hook');
  assert(html.includes('id="swaggerMarkdownLink"'), 'Help includes Swagger Markdown companion link hook');
  assert(html.includes('id="openApiSchemaLink"'), 'Help includes OpenAPI schema link hook');
  assert(html.includes('href="swagger.html"'), 'Swagger link opens local standard Swagger UI page');
  assert(html.includes('href="markdown_viewer.html?source=SWAGGER.md&amp;title=Swagger%20API"'), 'Swagger MD link opens local Markdown documentation');
  assert(html.includes('href="http://127.0.0.1:8000/openapi.json"'), 'API link opens the default OpenAPI page');
  assert(markdownViewerHtml.includes("'SWAGGER.md', 'Swagger API'"), 'Markdown viewer can render local Swagger Markdown');
  assert(swaggerHtml.includes('OpenBEXI Earth Orbit API'), 'local Swagger page has the API title');
  assert(swaggerHtml.includes('1.7.4'), 'local Swagger page displays the release version');
  assert(swaggerHtml.includes('OAS 3.0.3'), 'local Swagger page displays the OpenAPI version badge');
  assert(swaggerHtml.includes('Base URL / Schema Source'), 'local Swagger page displays base URL/schema context');
  assert(swaggerHtml.includes('<details class="operation get"'), 'local Swagger page has expandable GET operation rows');
  assert(swaggerHtml.includes('class="method get"'), 'local Swagger page has blue GET method badge markup');
  assert(swaggerHtml.includes('.method.post'), 'local Swagger page defines POST method color');
  assert(swaggerHtml.includes('.method.put'), 'local Swagger page defines PUT method color');
  assert(swaggerHtml.includes('.method.delete'), 'local Swagger page defines DELETE method color');
  [
    '/api/health',
    '/api/version',
    '/api/tle',
    '/api/satellites',
    '/api/satellite-metadata',
    '/api/satellite-metadata/{file_name}',
    '/api/decayed',
    '/openapi.json',
    '/docs'
  ].forEach(route => {
    assert(swaggerHtml.includes(route), `local Swagger page documents ${route}`);
  });
  assert(!swaggerHtml.includes('https://unpkg.com'), 'local Swagger page does not load Swagger UI from a CDN');
  assert(!swaggerHtml.includes('swagger-ui-dist'), 'local Swagger page does not require swagger-ui-dist for display');
  assert(!html.includes('Swagger and OpenAPI documentation are available from the connected Python server.'), 'prohibited Swagger/API sentence is absent from Help markup');
  assert(html.includes('for visualization, educational, and experimental purposes only'), 'Help includes legal disclaimer');
  assert(html.includes('satellite.js'), 'Help disclaimer mentions satellite.js limitations');

  assert(css.includes('.menu-accordion-heading'), 'CSS defines accordion headers');
  assert(css.includes('--menu-metal-yellow'), 'CSS defines a metallic yellow view style');
  assert(!css.includes('.menu-section-filters'), 'removed Filters section CSS is gone');
  assert(css.includes('--section-panel-bg'), 'CSS defines section-specific panel backgrounds');
  assert(css.includes('#controlsContainer h3.menu-accordion-heading[aria-expanded="true"]'), 'expanded accordion header contrast rule overrides global h3 color');
  assert(css.includes('color: #06182c !important;'), 'expanded accordion headers use dark high-contrast text');
  assert(css.includes('#controlsContainer h3.menu-accordion-heading[aria-expanded="true"] .toggle-icon'), 'expanded accordion chevron has an explicit readable color');
  assert(!css.includes('.menu-accordion-heading[aria-expanded="true"] {\n    color: #00aaff'), 'expanded accordion headers do not use light blue text');
  assert(css.includes('width: min(380px, calc(100vw - 20px))'), 'menu is thinner than the 1.5.4 accordion menu');
  assert(!css.includes('width: min(420px, calc(100vw - 20px))'), 'previous 420px menu width is no longer used');
  assert(css.includes('#satelliteCountDisplay'), 'satellite count has a dedicated style hook');
  assert(css.includes('.satellite-found-count'), 'satellite count has a heading-specific style hook');
  assert(css.includes('.satellite-filter-panel'), 'embedded Satellite Selection filters have dedicated CSS');
  assert(!css.includes('.debris-reset-row'), 'obsolete debris reset row CSS is removed');
  assert(css.includes('grid-template-columns: repeat(7, minmax(0, 1fr))'), 'orbit/category row is styled as one seven-button row');
  assert(css.includes('grid-template-columns: minmax(0, 1fr) auto auto'), 'search row styles search, Clear, and Reset Filters on one row');
  assert(css.includes('.reset-filters-inline-button'), 'inline Reset Filters button has dedicated CSS');
  assert(!css.includes('.filter-status-summary'), 'removed filter summary CSS is gone');
  assert(css.includes('color: #ff2a2a !important;'), 'satellite count is styled red');
  assert(css.includes('font-weight: 900;'), 'satellite count is styled bold');
  assert(css.includes('.menu-accordion-section .collapsible-content:not(.collapsed)'), 'long active accordion panels have scroll constraints');
  assert(css.includes('overflow-y: auto'), 'narrowed menu keeps scrollable overflow');
  assert(css.includes('.satellite-search-results'), 'satellite search results have dedicated CSS');
  assert(css.includes('position: fixed'), 'satellite search results can escape accordion clipping');
  assert(css.includes('z-index: 5000'), 'satellite search results render above menu elements');
  assert(css.includes('.satellite-search-results[hidden]'), 'hidden satellite results have an explicit CSS state');
  assert(css.includes('display: none !important;'), 'hidden satellite results are removed from layout');
  assert(css.includes('pointer-events: none !important;'), 'hidden satellite results cannot block controls');
  assert(!css.includes('#satelliteInfo'), 'obsolete Satellite Selection metadata/TLE table CSS is removed');
  assert(css.includes('.selected-satellite-detail-panel'), 'selected satellite detail panel has dedicated CSS');
  assert(css.includes('background: linear-gradient(180deg, rgba(6, 15, 28, 0.74), rgba(3, 8, 16, 0.54))'), 'selected satellite detail panel uses a transparent background');
  assert(css.includes('.selected-satellite-detail-section'), 'selected satellite detail panel has collapsible section CSS');
  assert(css.includes('.selected-satellite-detail-section summary'), 'selected satellite detail panel styles collapsible section toggles');
  assert(css.includes('.selected-satellite-tle-block'), 'selected satellite detail panel styles TLE details');
  assert(css.includes('width: auto;'), 'selected satellite detail panel lets JavaScript sync width to the UTC clock');
  assert(css.includes('#timeWarpBox'), 'time slider has responsive layout CSS');
  assert(!css.includes('.menu-time-warp-control'), 'removed menu Time x slider CSS is gone');
  assert(!css.includes('#menuTimeWarpSlider'), 'removed menu Time x slider id CSS is gone');
  assert(css.includes('#mercatorContainer.globe-overlay'), 'Globe + Mercator mode has a dedicated Mercator overlay style');
  assert(css.includes('#mercatorContainer.globe-overlay') && css.includes('bottom: 10px;') && css.includes('right: 10px;'), 'Mercator overlay is anchored to the bottom-right of the globe canvas');
  assert(css.includes('top: 50px !important'), 'narrow viewport time slider is moved away from top controls');
  assert(css.includes('top: 88px'), 'narrow viewport menu starts below the time slider');
  assert(css.includes('.menu-accordion-heading-satellite { border-left-color: #35b9a9; }'), 'Satellite keeps the legacy teal accent');
  assert(css.includes('.menu-accordion-heading-view { border-left-color: #f0b429; }'), 'View keeps the legacy yellow accent');
  assert(css.includes('.menu-accordion-heading-timelines { border-left-color: #d45187; }'), 'Timelines keeps the legacy pink accent');
  assert(!css.includes('.menu-section-other'), 'removed Other Selections section CSS is gone');
  assert(!css.includes('.menu-accordion-heading-other'), 'removed Other Selections header CSS is gone');
  assert(!css.includes('.other-selections-panel'), 'removed Other Selections panel CSS is gone');
  assert(!css.includes('.other-selections-heading'), 'Other header special text styling is removed');
  assert(!css.includes('.menu-accordion-heading-settings'), 'Settings accordion accent CSS is removed');
  assert(css.includes('.menu-accordion-heading-share { border-left-color: #6fd08c; }'), 'Share keeps a dedicated legacy-style accent');
  assert(css.includes('.menu-accordion-heading-help { border-left-color: #a98cff; }'), 'Help keeps a dedicated legacy-style accent');
  assert(css.includes('.server-status-button'), 'server status has dedicated CSS');
  assert(css.includes('.menu-header-row'), 'menu top row has dedicated CSS');
  assert(css.includes('--menu-header-control-height: 30px;'), 'menu header controls share a fixed alignment height');
  assert(css.includes('height: var(--menu-header-control-height);'), 'Close and server controls share the header control height');
  assert(css.includes('margin: 0 0 10px 54px;'), 'menu header row reserves aligned space for the external Close button');
  assert(css.includes('.server-status-icon'), 'server status icon has dedicated CSS');
  assert(css.includes('.server-state-connected .server-status-icon'), 'server connected icon state has CSS');
  assert(css.includes('.server-state-disconnected .server-status-icon'), 'server disconnected icon state has CSS');
  assert(css.includes('.server-state-error .server-status-icon'), 'server error icon state has CSS');
  assert(css.includes('.share-panel'), 'Share panel has dedicated CSS');
  assert(css.includes('.share-action-row'), 'Share actions have dedicated CSS');
  assert(css.includes('.share-image-preview-frame'), 'Share image preview has dedicated CSS');
  assert(css.includes('.share-image-action-row'), 'Share image actions have dedicated CSS');
  assert(css.includes('.api-docs-panel'), 'API docs panel has dedicated CSS');
  assert(css.includes('.api-docs-link.is-disabled'), 'API docs disabled state has CSS');
  assert(css.includes('.help-panel'), 'Help panel has dedicated CSS');
  assert(css.includes('.help-smart-grid'), 'Help document grid has dedicated CSS');
  assert(css.includes('.help-doc-card'), 'Help document cards have dedicated CSS');
  assert(!css.includes('.help-markdown-panel'), 'inline Help Markdown preview CSS is removed');
  assert(!css.includes('.help-markdown-content'), 'inline Help Markdown content CSS is removed');
  assert(css.includes('.help-disclaimer'), 'Help disclaimer has dedicated CSS');
  assert(css.includes('.filter-chip input[type="checkbox"]:checked + span'), 'selected tag chips have a distinct active style');
  assert(css.includes(':focus-visible'), 'menu controls have visible focus styling');
  assert(css.includes('@media (max-width: 560px)'), 'menu has narrow viewport behavior');
  assert(css.includes('.view-checkbox-table'), 'View main controls have 3x3 table CSS');
  assert(css.includes('grid-template-columns: repeat(3, minmax(78px, 1fr))'), 'View main controls use three aligned columns');
  assert(css.includes('.view-checkbox-empty'), 'View main control table has styled empty cells');
  assert(css.includes('.view-control-row-three'), 'View sub-option rows keep three-column CSS');
  assert(css.includes('.solar-system-options[hidden]'), 'Solar System sub-controls are hidden by default through CSS');
  assert(css.includes('.solar-system-selection-summary'), 'Solar System selection summary has dedicated CSS');
  assert(css.includes('.solar-system-planet-hud'), 'Solar System selected planet HUD has dedicated CSS');
  assert(css.includes('.solar-system-hud-body'), 'Solar System selected planet HUD body has dedicated clock-aligned CSS');
  assert(css.includes('.solar-system-hud-row'), 'Solar System selected planet HUD rows have dedicated layout CSS');
  assert(css.includes('font-family: "SF Mono", "Roboto Mono", "Fira Mono", Menlo, Consolas, monospace;'), 'Solar System HUD uses the UTC clock monospace font family');
  assert(css.includes('.stars-milky-way-options[hidden]'), 'Stars & Milky Way sub-controls can be hidden when the parent toggle is off');
  assert(css.includes('.star-catalog-summary'), 'bundled star catalog summary has dedicated CSS');
  assert(!css.includes('.star-magnitude-control'), 'removed Magnitude limit control CSS is gone');
  assert(css.includes('font-size: 13px'), 'Stars & Milky Way controls use readable menu text');
  assert(css.includes('.satellite-shortcut-row'), 'Satellite shortcut row has dedicated CSS');
  assert(css.includes('.satellite-shortcut-button'), 'Satellite shortcut buttons have dedicated CSS');

  assert(indexHtml.includes('MENU_COLLAPSE_STORAGE_KEY'), 'index persists collapsed accordion sections');
  assert(!indexHtml.includes('menuTimeWarpSlider'), 'index no longer reads the removed menu Time x slider');
  assert(!indexHtml.includes('menuTimeWarpVal'), 'index no longer reads the removed menu Time x value');
  assert(indexHtml.includes('sliderValueToTimeWarp'), 'index converts slider values through a shared helper');
  assert(indexHtml.includes('updateTimeWarpControls'), 'index keeps the canvas Time x slider synchronized with state');
  assert(indexHtml.includes('timeWarpSlider?.addEventListener'), 'canvas Time x slider drives simulation speed');
  assert(indexHtml.includes("mercatorContainer.classList.toggle('globe-overlay', show3D)"), 'Mercator overlay class is enabled when Globe and Mercator are both selected');
  assert(indexHtml.includes("mercatorContainer.classList.remove('fullscreen', 'globe-overlay')"), 'Mercator view classes are cleared when Mercator is disabled');
  assert(indexHtml.includes('id="selectedSatelliteDetailPanel"'), 'index defines the selected satellite detail panel');
  assert(indexHtml.includes('updateSelectedSatelliteDetailPanel'), 'index updates the right-side selected satellite detail panel');
  assert(indexHtml.includes('syncSelectedSatelliteDetailPanelWidth'), 'index syncs the selected detail panel width to the UTC clock');
  assert(indexHtml.includes("solarSystemPlanetHudElement || document.getElementById('solarSystemPlanetHud')"), 'index syncs the Solar System HUD width to the UTC clock');
  assert(indexHtml.includes('panel.style.width = `${clockWidth}px`'), 'right-side panels are assigned the clock measurement width');
  assert(indexHtml.includes('panel.style.right = `${clockRight}px`'), 'right-side panels align horizontally with the UTC clock');
  assert(indexHtml.includes('panel.style.top = `${panelTop}px`'), 'right-side panels align directly below the UTC clock');
  assert(indexHtml.includes('SELECTED_DETAIL_DUPLICATE_KEYS'), 'index excludes duplicated selected-detail fields from the metadata table');
  assert(indexHtml.includes("'tle_line1'"), 'TLE line 1 is excluded from duplicate metadata rows');
  assert(indexHtml.includes("'tle_line2'"), 'TLE line 2 is excluded from duplicate metadata rows');
  assert(indexHtml.includes('selected-satellite-tle-block'), 'selected satellite detail panel includes TLE details');
  assert(indexHtml.includes('solar-system-hud-row'), 'Solar System HUD uses compact row layout');
  assert(indexHtml.includes('<details class="selected-satellite-detail-section selected-satellite-data-section" open>'), 'selected satellite data section is expanded by default');
  assert(indexHtml.includes('<details class="selected-satellite-detail-section selected-satellite-tle-section" open>'), 'selected satellite TLE section is expanded by default');
  assert(indexHtml.includes('<span>Satellite data</span>'), 'selected satellite data section has a visible toggle label');
  assert(indexHtml.includes('<span>TLE details</span>'), 'selected satellite TLE section has a visible toggle label');
  assert(indexHtml.includes('Collapse details'), 'satellite data default-open state uses a matching summary hint');
  assert(indexHtml.includes('Collapse TLE'), 'TLE details default-open state uses a matching summary hint');
  assert(indexHtml.includes('selectedSatelliteModelSourceDetail'), 'selected satellite panel computes model source attribution');
  assert(indexHtml.includes('<details class="selected-satellite-detail-section selected-satellite-source-section" open>'), 'selected satellite source detail section is expanded by default');
  assert(indexHtml.includes('<span>Source detail</span>'), 'selected satellite source detail section has a visible toggle label');
  assert(indexHtml.includes('selected-satellite-source-detail'), 'selected satellite source detail text has dedicated styling');
  assert(indexHtml.includes('https://sketchfab.com/malacodart'), 'Starlink model source attribution is present');
  assert(indexHtml.includes('CC Attribution / Creative Commons Attribution'), 'Starlink license attribution is present');
  assert(indexHtml.includes('https://github.com/nasa/NASA-3D-Resources'), 'ISS model source attribution is present');
  assert(indexHtml.includes('NASA (National Aeronautics and Space Administration)'), 'ISS courtesy attribution is present');
  assert(css.includes('.selected-satellite-source-detail'), 'source detail attribution has dedicated CSS');
  assert(css.includes('color: #ff3b30'), 'source detail attribution is red');
  assert(css.includes('font-weight: 800'), 'source detail attribution is bold');
  assert(!indexHtml.includes('updateSatelliteInfo'), 'index no longer updates a menu-side metadata/TLE table');
  assert(!indexHtml.includes('loadHelpMarkdown(source, title)'), 'index no longer renders README and Releases History Markdown inside Help');
  assert(!indexHtml.includes('setupHelpMarkdownLink(readmeMarkdownLink)'), 'README Help action is no longer wired to inline Markdown renderer');
  assert(markdownViewerHtml.includes('renderMarkdown(markdown'), 'Markdown viewer renders Help Markdown in a separate page');
  assert(markdownViewerHtml.includes('escapeHtml(value'), 'Markdown viewer escapes raw HTML');
  assert(markdownViewerHtml.includes('safeMarkdownHref'), 'Markdown viewer sanitizes Markdown links');
  assert(markdownViewerHtml.includes('ALLOWED_MARKDOWN_SOURCES'), 'Markdown viewer restricts allowed source files');
  assert(indexHtml.includes('updateSelectedSatelliteControlsVisibility'), 'index gates selected-satellite controls by selection state');
  assert(indexHtml.includes("'shareContent'"), 'Share starts collapsed with other non-default accordion sections');
  assert(indexHtml.includes("'helpContent'"), 'Help starts collapsed with other non-default accordion sections');
  assert(indexHtml.includes('checkAndLoadServerTleData'), 'index implements server connection and TLE fallback flow');
  assert(indexHtml.includes('tleDataOverride: serverTleData'), 'index passes server TLE data to the existing TLE loader only when available');
  assert(indexHtml.includes('copyCurrentShareLink'), 'index implements Copy Link behavior');
  assert(indexHtml.includes('preserveDrawingBuffer: true'), 'WebGL renderer keeps drawing buffer for Share image capture');
  assert(indexHtml.includes('canvas.toBlob'), 'Share image capture uses canvas.toBlob');
  assert(indexHtml.includes('ClipboardItem'), 'Share image copy checks ClipboardItem support');
  assert(indexHtml.includes('Canvas image capture is unavailable'), 'Share image capture has a fallback message');
  assert(indexHtml.includes('navigator.canShare({ files: [imageFile] })'), 'Native Share includes image only when canShare supports it');
  assert(indexHtml.includes('applyPendingShareStateAfterSatelliteLoad'), 'index restores share state after satellite data loads');
  assert(indexHtml.includes('updateApiDocsState'), 'index updates Swagger/API docs links');
  assert(indexHtml.includes("const swaggerUiUrl = 'swagger.html'"), 'index routes Swagger docs to the local static UI page');
  assert(indexHtml.includes('swaggerMarkdownLink'), 'index preserves the Swagger Markdown companion link');
  assert(indexHtml.includes('Swagger UI opens locally without the Python server'), 'offline Swagger UI docs remain available without the Python server');
  assert(!indexHtml.includes('Swagger and OpenAPI documentation are available from the connected Python server.'), 'prohibited Swagger/API status sentence is not emitted');
  assert(indexHtml.includes('ensureYPRControlsVisibleForSelection'), 'index preserves YPR controls after satellite selection');
  assert(!/yawSlider\.value\s*=\s*0/.test(indexHtml), 'satellite selection does not reset yaw slider value');
  assert(!/pitchSlider\.value\s*=\s*0/.test(indexHtml), 'satellite selection does not reset pitch slider value');
  assert(!/rollSlider\.value\s*=\s*0/.test(indexHtml), 'satellite selection does not reset roll slider value');
  assert(indexHtml.includes('buildSatelliteSearchMatches(filteredTLEs, satelliteSearchInput.value'), 'index uses shared satellite search matching');
  assert(indexHtml.includes('resetFiltersToDefaults'), 'index implements filter reset');
  assert(indexHtml.includes('setShowOnlySelectedSatellite(true)'), 'selecting a satellite auto-enables show-only-selected mode');
  assert(indexHtml.includes('setShowOnlySelectedSatellite(false)'), 'clearing a satellite disables show-only-selected mode');
  assert(indexHtml.includes('showOnlySelectedSatelliteCheckbox.checked'), 'show-only-selected checkbox is synchronized with simParams');
  assert(indexHtml.includes('enableHighDefForSelectedSatelliteIfNeeded(tleSatData)'), 'non-MEO/GEO selections auto-enable High Def Earth');
  assert(indexHtml.includes("orbitType === 'MEO' || orbitType === 'GEO'"), 'MEO and GEO selections do not force High Def on');
  assert(indexHtml.includes('clearSatelliteSearchInputForNextSelection'), 'search field clears the prior selected label before a new search');
  assert(indexHtml.includes('satelliteSearchClearedForNextSelection'), 'search clearing preserves the current selected satellite');
  assert(indexHtml.includes('findFirstStarlinkSatellite'), 'Satellite Selection shortcut can locate the first Starlink satellite');
  assert(indexHtml.includes('findIssSatellite'), 'Satellite Selection shortcut can locate ISS/ZARYA');
  assert(indexHtml.includes('selectSatelliteViaShortcut'), 'Satellite Selection shortcuts use the normal satellite selection path');
  assert(indexHtml.includes('starlinkShortcutState(findFirstStarlinkSatellite())'), 'Starlink shortcut uses dynamic state helper');
  assert(indexHtml.includes('issShortcutState(findIssSatellite())'), 'ISS shortcut uses dynamic state helper');
  assert(indexHtml.includes("s?.norad_id?.toString() === ISS_NORAD_ID"), 'ISS shortcut prefers NORAD 25544');
  assert(indexHtml.includes('iss-velocity-pitch-nadir-frame'), 'ISS selected model uses pitch-nadir orbital-frame orientation mode');
  assert(indexHtml.includes("const ISS_MODEL_AXIS_MAPPING = 'x-velocity-y-nadir-z-negative-crosstrack'"), 'ISS model maps pitch axis to nadir');
  assert(indexHtml.includes('ISS_MODEL_EARTH_FACING_AXIS = { x: 0, y: 1, z: 0 }'), 'ISS fallback nadir orientation uses pitch axis as Earth-facing');
  assert(indexHtml.includes('+Y pitch/nadir toward Earth'), 'ISS diagnostics document pitch axis pointing toward Earth');
  assert(indexHtml.includes('pitchAxisEarthFacing = true'), 'ISS diagnostics mark pitch as Earth-facing');
  assert(indexHtml.includes('calibrationPitchDeg'), 'ISS orientation diagnostics include pitch calibration');
  assert(indexHtml.includes('calibrationRollDeg'), 'ISS orientation diagnostics include roll calibration');
  assert(indexHtml.includes('selectedSatelliteOrientationBias(isIssModel)'), 'selected model orientation uses a model-specific control-bias helper');
  assert(indexHtml.includes("controlMapping: isIssModel ? 'iss-yaw-pitch-swapped'"), 'ISS selected model swaps yaw and pitch control mapping');
  assert(indexHtml.includes('yawDeg: isIssModel ? simParams.pitchDeg : simParams.yawDeg'), 'ISS yaw input uses the pitch slider value');
  assert(indexHtml.includes('pitchDeg: isIssModel ? simParams.yawDeg : simParams.pitchDeg'), 'ISS pitch input uses the yaw slider value');
  assert(indexHtml.includes('rollDeg: simParams.rollDeg'), 'ISS roll input remains unchanged');
  assert(indexHtml.includes('detailedSatelliteModel.userData.appliedYawDeg = orientationBias.yawDeg'), 'ISS diagnostics expose applied yaw after swap');
  assert(indexHtml.includes('detailedSatelliteModel.userData.appliedPitchDeg = orientationBias.pitchDeg'), 'ISS diagnostics expose applied pitch after swap');
  assert(indexHtml.includes('visible = !!currentSelectedSatellite'), 'show-only visibility is not constrained by current filters');
  assert(indexHtml.includes('earthInView: selectedCameraFrameKeepsEarthInView'), 'selected-satellite camera metadata checks Earth remains visible');
  assert(indexHtml.includes('function computeSelectedModelObserverFrame'), 'selected detailed model uses a reusable observer-frame calculation');
  assert(indexHtml.includes('selectedStarlinkCameraFrameOptions(targetPos, propagation)'), 'Starlink camera frame is recomputed from current propagation');
  assert(indexHtml.includes('updateSelectedModelTracking(selectedPropagation)'), 'selected model tracking receives the current propagation state');
  assert(indexHtml.includes('selectedModelTracking.localCameraOffset'), 'selected model tracking preserves user zoom/orbit offset');
  assert(indexHtml.includes('selectedFrameLocalToCameraOffset'), 'selected model tracking reapplies user camera offset in the current observer frame');
  assert(indexHtml.includes('cameraMove.endCamPos.copy(trackingFrame.cameraPosition)'), 'selected model fly-to target follows the recomputed observer frame during time changes');
  assert(indexHtml.includes('SELECTED_ORBIT_ALIGNMENT_TOLERANCE_SCENE_UNITS = 0.01'), 'selected model orbit alignment tolerance is explicit');
  assert(indexHtml.includes('orbitAlignmentDebugEnabled'), 'selected model orbit alignment debug mode exists');
  assert(indexHtml.includes('function setDetailedSatelliteModelPositionFromPropagation'), 'selected model root position uses a canonical propagation helper');
  assert(indexHtml.includes('selectedOrbitNearestPointDistance(modelWorldPosition)'), 'selected model diagnostics measure distance to selected orbit line');
  assert(indexHtml.includes('currentSelectedSatellite.mesh.position.copy(propagatedScenePosition)'), 'hidden selected sprite is synchronized with the detailed model root');
  assert(indexHtml.includes('rootToPropagatedDistanceSceneUnits'), 'selected model diagnostics report root-to-propagated distance');
  assert(!indexHtml.includes('eciToSceneVector(detailedSatelliteModel.position'), 'selected model root position is not written outside the canonical helper');
  assert(indexHtml.includes('const EARTH_SURFACE_MIN_ZOOM_KM = 100'), 'Earth-mode minimum zoom is defined as 100 km above surface');
  assert(indexHtml.includes('const EARTH_MODE_MIN_DISTANCE = EARTH_SCENE_RADIUS + EARTH_SURFACE_MIN_ZOOM_KM * KM_TO_SCENE_UNITS'), 'Earth min zoom is Earth radius plus 100 km, not distance from center');
  assert(indexHtml.includes('const SAFE_MAX_CONTROL_DISTANCE = EARTH_SCENE_RADIUS * 100000'), 'maximum zoom is very large and finite');
  assert(indexHtml.includes('const SAFE_CAMERA_FAR = Math.max'), 'camera far plane has a safe finite bound');
  assert(indexHtml.includes('controls.enablePan = false'), 'OrbitControls panning is disabled so target cannot drift');
  assert(indexHtml.includes('function enforceSceneOrigin()'), 'index enforces Earth scene origin');
  assert(indexHtml.includes('earthMesh.position.set(0, 0, 0)'), 'Earth mesh is pinned at scene origin');
  assert(indexHtml.includes('function enforceActiveControlTarget()'), 'index defines active camera target priority enforcement');
  assert(indexHtml.includes('controls.target.copy(moon.position)'), 'Moon mode targets the Moon position');
  assert(indexHtml.includes('controls.target.copy(mars.position)'), 'Mars mode targets the Mars position');
  assert(indexHtml.includes("import { MARS_TEXTURE_URL, createMars, updateMars } from './js/MarsFrameLoader.js';"), 'index imports Mars frame helpers and the shared texture path');
  assert(indexHtml.includes('textureUrl: MARS_TEXTURE_URL'), 'index creates Mars with the shared optimized Mars texture path');
  assert(indexHtml.includes('id="marsTextureLoading"'), 'index includes a Mars texture loading status panel');
  assert(indexHtml.includes('Loading Mars map/texture...'), 'Mars texture loading panel has the required label');
  assert(indexHtml.includes('onTextureLoadProgress: handleMarsTextureProgress'), 'index wires Mars texture progress callbacks');
  assert(indexHtml.includes("onTextureLoadStart: () => recordMarsTextureLoadState('loading', 0)"), 'Mars startup texture load records state without directly showing the progress panel');
  assert(!indexHtml.includes("onTextureLoadStart: () => setMarsTextureLoadingState('loading', 0)"), 'Mars startup texture load does not directly show the progress panel');
  assert(indexHtml.includes('function shouldShowMarsTextureProgress()'), 'index gates visible Mars texture progress by active context');
  assert(indexHtml.includes("return simParams.otherSelection === 'Mars'"), 'Mars texture progress is visible only when Mars is active');
  assert(indexHtml.includes('showMarsTextureProgressForSelection()'), 'selecting Mars explicitly shows the centered progress panel');
  assert(indexHtml.includes('hideMarsTextureLoadingPanel()'), 'leaving Mars hides the Mars progress panel');
  assert(indexHtml.includes("if (!shouldShowMarsTextureProgress()) return;"), 'Mars Mercator progress events are ignored unless Mars is active');
  assert(indexHtml.includes('MARS_TEXTURE_LOADING_MIN_VISIBLE_MS = 1600'), 'Mars texture loading panel stays visible long enough for cached/local loads');
  assert(indexHtml.includes("window.addEventListener('openbexi:mars-map-loading'"), 'index listens for Mars Mercator map loading progress');
  assert(indexHtml.includes('Mars texture failed to load. Using fallback Mars color.'), 'Mars texture load failure has a visible fallback message');
  assert(indexHtml.includes('MARS_CAMERA_DISTANCE_MULTIPLIER = 1.45'), 'Mars observer starts close to the Mars globe');
  assert(indexHtml.includes('distanceMultiplier: simParams.otherSelection === \'Mars\' ? MARS_CAMERA_DISTANCE_MULTIPLIER : 4'), 'Mars selection uses the closer observer distance');
  assert(indexHtml.includes('mercatorUsesEarthSatellites = simParams.otherSelection !== \'Mars\''), 'Mercator suppresses Earth satellite overlays in Mars context');
  assert(indexHtml.includes("simParams.otherSelection === 'Mars'"), 'index handles internal Mars context state');
  assert(indexHtml.includes('if (mars) updateMars(mars, SIM_DATE)'), 'index updates Mars each frame');
  assert(indexHtml.includes('updateMars(mars, SIM_DATE);'), 'index initializes Mars position before the first selectable frame');
  assert(indexHtml.includes("from './js/solarSystemOverviewLoader.js'"), 'index imports the integrated Solar System module');
  assert(indexHtml.includes('solarSystemOverview: false'), 'Solar System mode is disabled by default in simParams');
  assert(indexHtml.includes('solarSystemPlanetLabels: true'), 'Solar System planet labels default enabled inside mode');
  assert(indexHtml.includes('solarSystemOrbitPaths: true'), 'Solar System orbit paths default enabled inside mode');
  assert(indexHtml.includes('solarSystemPlanetTextures: true'), 'Solar System planet textures default enabled inside mode');
  assert(indexHtml.includes('solarSystemSunGlow: true'), 'Solar System sun glow default enabled inside mode');
  assert(indexHtml.includes('function setSolarSystemOverviewMode'), 'index defines explicit Solar System mode state transitions');
  assert(indexHtml.includes('snapshotSolarSystemPreviousState'), 'Solar System mode stores previous app state');
  assert(indexHtml.includes('restoreSolarSystemPreviousState'), 'Solar System mode can restore previous app state');
  assert(indexHtml.includes('setSolarSystemEarthLayerVisibility'), 'Solar System mode gates Earth-specific layers');
  assert(indexHtml.includes('activateEarthFromSolarSystemSelection'), 'Solar System Earth selection exits to Globe mode');
  assert(indexHtml.includes('activateMoonFromSolarSystemSelection'), 'Solar System Moon selection exits to Moon mode');
  assert(indexHtml.includes('activateMarsFromSolarSystemSelection'), 'Solar System Mars selection exits to Mars mode');
  assert(indexHtml.includes("if (planetName === 'Moon')"), 'Solar System click handling maps Moon to Moon mode');
  assert(indexHtml.includes('focusSolarSystemPlanetInMode'), 'Solar System can focus non-Earth/Mars planets');
  assert(indexHtml.includes('pickSolarSystemPlanet'), 'Solar System mode supports planet/label click selection');
  assert(indexHtml.includes('handleSolarSystemKeydown'), 'Solar System mode supports Escape handling');
  assert(indexHtml.includes('Solar System Planet'), 'index defines a selected planet HUD');
  assert(indexHtml.includes('showFootprint: !!simParams.showFootprint && !simParams.solarSystemOverview'), 'Solar System mode suppresses footprints');
  assert(indexHtml.includes('simParams.viewMercator && !simParams.solarSystemOverview'), 'Solar System mode suppresses Mercator rendering');
  assert(indexHtml.includes('showSun:  simParams.showDayNight && simParams.view3D && !simParams.solarSystemOverview'), 'Solar System mode suppresses Earth day/night sun layer');
  assert(indexHtml.includes("import { BRIGHT_STARS_DEMO } from './data/stars/bright-stars-demo.js';"), 'index imports the real RA/Dec demo star catalog');
  assert(!indexHtml.includes('MAX_INTEGRATED_STAR_MAGNITUDE_LIMIT'), 'index no longer imports the integrated magnitude limit cap');
  assert(indexHtml.includes('showStarsMilkyWay: true'), 'Stars & Milky Way is enabled by default in simParams');
  assert(indexHtml.includes('showRaDecGrid: false'), 'RA/Dec Grid is disabled by default in simParams');
  assert(indexHtml.includes('showBrightStarLabels: false'), 'Bright Labels is disabled by default in simParams');
  assert(indexHtml.includes('showStarAtmosphere: false'), 'Atmosphere is disabled by default in simParams');
  assert(!indexHtml.includes('starMagnitudeLimit'), 'main app no longer keeps user-facing star magnitude state');
  assert(indexHtml.includes('const MILKY_WAY_TEXTURE_URL = \'obj/Textures/starmap-4k.jpg\''), 'main app uses the local Milky Way texture path');
  assert(indexHtml.includes('function initStarsMilkyWayLayer()'), 'index initializes the optional Stars & Milky Way layer');
  assert(indexHtml.includes('new THREE.Points(geometry, starMaterial)'), 'Stars are rendered as a single THREE.Points layer');
  assert(indexHtml.includes('new THREE.SphereGeometry(STAR_SKY_RADIUS * 1.02'), 'Milky Way renders as a celestial sphere');
  assert(indexHtml.includes('buildStarBufferData(BRIGHT_STARS_DEMO'), 'star field uses the real RA/Dec demo catalog');
  assert(indexHtml.includes('magnitudeLimit: Number.POSITIVE_INFINITY'), 'main app renders the full bundled star catalog without a user-controlled magnitude limit');
  assert(indexHtml.includes('starPoints.userData.visibleStarCount = starData.stars.length'), 'main app records visible bundled star count');
  assert(indexHtml.includes('Displaying ${BRIGHT_STARS_DEMO.length} bundled reference stars'), 'main app computes catalog summary from catalog length');
  assert(indexHtml.includes('STAR_LABEL_CANVAS_WIDTH = 768'), 'bright star labels use a high-resolution canvas');
  assert(indexHtml.includes('STAR_LABEL_FONT_PX = 72'), 'bright star labels use readable text size');
  assert(indexHtml.includes('STAR_LABEL_WORLD_HEIGHT_FACTOR = 0.035'), 'bright star labels use a larger world scale');
  assert(indexHtml.includes('ctx.strokeText(text'), 'bright star labels draw outlined text for contrast');
  assert(indexHtml.includes('function updateStarCatalogSummaryVisibility()'), 'index has a dedicated star catalog summary visibility helper');
  assert(indexHtml.includes('const visible = !!simParams.showStarsMilkyWay && !!simParams.showBrightStarLabels'), 'star catalog summary is shown only when Stars & Milky Way and Bright Labels are enabled');
  assert(indexHtml.includes('starCatalogSummaryElement.hidden = !visible'), 'star catalog summary hides when either required checkbox is off');
  assert(indexHtml.includes("starCatalogSummaryElement.setAttribute('aria-hidden', visible ? 'false' : 'true')"), 'star catalog summary updates aria-hidden with visibility');
  assert(indexHtml.includes('function syncStarsMilkyWayControlsVisibility()'), 'index hides/shows star sub-controls');
  assert(indexHtml.includes('starsMilkyWayOptionsElement.hidden = !visible'), 'star sub-controls are hidden when Stars & Milky Way is off');
  assert(!indexHtml.includes('starMagnitudeLimitSliderElement'), 'removed Magnitude limit input listener is gone');
  assert(indexHtml.includes('const showSky = !!simParams.showStarsMilkyWay && !simParams.solarSystemOverview'), 'Stars & Milky Way main layer is hidden while Solar System mode provides its own sky');
  assert(indexHtml.includes('milkyWaySphere.visible = showSky'), 'Milky Way is visible only when Stars & Milky Way is enabled');
  assert(indexHtml.includes('starPoints.visible = showSky'), 'Star points are visible only when Stars & Milky Way is enabled');
  assert(indexHtml.includes('raDecGrid.visible = showSky && !!simParams.showRaDecGrid'), 'RA/Dec grid depends on Stars & Milky Way and its checkbox');
  assert(indexHtml.includes('brightStarLabelGroup.visible = showSky && !!simParams.showBrightStarLabels'), 'Bright labels depend on Stars & Milky Way and its checkbox');
  assert(indexHtml.includes('starAtmosphereMesh.visible = showSky && !!simParams.showStarAtmosphere'), 'Atmosphere depends on Stars & Milky Way and its checkbox');
  assert(indexHtml.includes('controls.target.set(0, 0, 0)'), 'Earth mode targets the Earth center');
  assert(!indexHtml.includes('moon.position.set(0, 0, 0)'), 'Moon mode does not move the Moon object to scene origin');
  assert(!indexHtml.includes('mars.position.set(0, 0, 0)'), 'Mars mode does not move the Mars object to scene origin');
  assert(marsFrameLoader.includes("MARS_TEXTURE_SOURCE_URL = 'textures/March.jpg'"), 'Mars loader preserves the original source texture path');
  assert(marsFrameLoader.includes("MARS_TEXTURE_URL = 'textures/March_8k.jpg'"), 'Mars loader uses the optimized browser-safe 8K runtime texture');
  assert(marsFrameLoader.includes('onTextureLoadStart'), 'Mars loader exposes a texture load start callback');
  assert(marsFrameLoader.includes('onTextureLoadProgress'), 'Mars loader exposes texture progress callbacks');
  assert(marsFrameLoader.includes('onTextureLoadComplete'), 'Mars loader exposes texture complete callbacks');
  assert(marsFrameLoader.includes('onTextureLoadError'), 'Mars loader exposes texture error callbacks');
  assert(mercatorMapLoader.includes("import {MARS_TEXTURE_URL} from './MarsFrameLoader.js';"), 'Mercator loader imports the Mars texture path');
  assert(mercatorMapLoader.includes('mercatorBackgroundUrlForContext'), 'Mercator loader resolves background texture from active context');
  assert(mercatorMapLoader.includes("simParams?.otherSelection === 'Mars'"), 'Mercator loader detects Mars context');
  assert(mercatorMapLoader.includes('Mars Mercator map'), 'Mercator loader labels the Mars map context');
  assert(mercatorMapLoader.includes('return isMarsMercatorContext(simParams) ? MARS_TEXTURE_URL : earthConfig.textureLight'), 'Mercator loader uses Mars texture instead of Earth texture in Mars context');
  assert(mercatorMapLoader.includes("CustomEvent('openbexi:mars-map-loading'"), 'Mercator loader emits Mars map loading events');
  assert(css.includes('.planet-texture-loading'), 'CSS styles the Mars texture loading progress panel');
  assert(css.includes('left: 50%;') && css.includes('top: 50%;') && css.includes('transform: translate(-50%, -50%)'), 'Mars texture loading progress panel is centered on the canvas');
  assert(css.includes('.planet-texture-progress-fill'), 'CSS styles the Mars texture loading progress fill');
  assert(css.includes('.mapBackground[data-map-body="Mars"].fallback-css'), 'CSS provides a Mars-specific Mercator fallback texture state');
  assert(indexHtml.includes('if (currentSelectedSatellite || detailedSatelliteModel?.visible) return;'), 'selected satellite target priority is preserved over Earth/Moon target enforcement');
  assert(indexHtml.includes('camera.far = SAFE_CAMERA_FAR'), 'camera far plane is restored to the safe finite bound');
  assert(indexHtml.includes('isSatelliteDropdownOpen'), 'satellite search uses explicit dropdown open state');
  assert(indexHtml.includes('positionSatelliteSearchResults'), 'satellite search results are positioned over menu elements');
  assert(indexHtml.includes('document.body.appendChild(satelliteSearchResults)'), 'satellite search results are portaled outside accordion clipping');
  assert(indexHtml.includes('insideResults = satelliteSearchResults?.contains(event.target)'), 'outside-click handling preserves clicks inside portaled results');
  assert(indexHtml.includes('document.addEventListener(\'pointerdown\''), 'outside clicks close satellite search results');
  assert(indexHtml.includes("event.key === 'Tab'"), 'Tab closes satellite search results without trapping focus');
  assert(indexHtml.includes('if (forceOpen) isSatelliteDropdownOpen = true'), 'only explicit user actions open satellite search results');
  assert(indexHtml.includes('aria-activedescendant'), 'satellite search supports active descendant keyboard state');
  assert(indexHtml.includes('syncExclusiveTimelineSelection'), 'index enforces mutually exclusive timeline checkboxes');
  assert(indexHtml.includes("hideTimelineById('reentryTimelineToggle')"), 'launch selection hides re-entry timeline');
  assert(indexHtml.includes("hideTimelineById('launchTimelineToggle')"), 're-entry selection hides launch timeline');
  assert(indexHtml.includes('handle.setVisible(false)'), 'timeline exclusivity hides the inactive HUD through timeline handles');
  assert(launchTimeline.includes("toggle?.type === 'checkbox'"), 'launch timeline supports checkbox toggles');
  assert(reentryTimeline.includes("toggle?.type === 'checkbox'"), 're-entry timeline supports checkbox toggles');
  assert(launchTimeline.includes('setVisible: setVisibility'), 'launch timeline exposes explicit visibility control');
  assert(reentryTimeline.includes('setVisible: setVisibility'), 're-entry timeline exposes explicit visibility control');
  assert(launchTimeline.includes('isVisible()'), 'launch timeline exposes visibility state');
  assert(reentryTimeline.includes('isVisible()'), 're-entry timeline exposes visibility state');

  console.log('menuUx tests passed');
}

run();
