import assert from 'assert';
import fs from 'fs';
import { satelliteMenuLoader } from '../js/SatelliteMenuLoader.js';

function indexOfOrFail(text, needle, message) {
  const index = text.indexOf(needle);
  assert(index >= 0, message);
  return index;
}

function run() {
  const html = satelliteMenuLoader();
  const css = fs.readFileSync('css/style.css', 'utf8');
  const indexHtml = fs.readFileSync('index.html', 'utf8');
  const markdownViewerHtml = fs.readFileSync('markdown_viewer.html', 'utf8');
  const launchTimeline = fs.readFileSync('js/ganttTimelineLoader.js', 'utf8');
  const reentryTimeline = fs.readFileSync('js/reentryTimeline.js', 'utf8');
  const marsFrameLoader = fs.readFileSync('js/MarsFrameLoader.js', 'utf8');
  const mercatorMapLoader = fs.readFileSync('js/mercatorMapLoader.js', 'utf8');

  assert(!html.includes('role="tablist"'), 'main menu no longer exposes a tablist');
  assert(!html.includes('role="tab"'), 'main menu no longer exposes tab buttons');
  assert(!html.includes('role="tabpanel"'), 'main menu no longer exposes tab panels');
  assert(!html.includes('data-tab-target'), 'main menu no longer uses tab target wiring');
  assert(!html.includes('menu-tab-rail'), 'vertical tab rail markup is removed');
  assert(!css.includes('.menu-tab-rail'), 'vertical tab rail CSS is removed');
  assert(!indexHtml.includes('MENU_TAB_STORAGE_KEY'), 'selected tab persistence is removed');
  assert(!indexHtml.includes('activateMenuTabById'), 'tab activation logic is removed');

  assert(html.includes('class="menu-accordion"'), 'menu uses stacked accordion markup');
  assert(html.includes('menu-accordion-heading'), 'accordion headers are present');
  assert(html.includes('role="button"'), 'accordion headers expose button semantics');
  assert(html.includes('aria-controls="filtersContent"'), 'Filters header controls its content');
  assert(html.includes('aria-controls="satelliteSelectionContent"'), 'Satellite header controls its content');
  assert(html.includes('aria-expanded="true" data-collapsible-target="viewContent"'), 'Views & Time starts expanded in markup');
  assert(html.includes('aria-expanded="true" data-collapsible-target="satelliteSelectionContent"'), 'Satellite Selection starts expanded in markup');
  assert(html.includes('aria-expanded="true" data-collapsible-target="filtersContent"'), 'Filters starts expanded in markup');
  assert(html.includes('data-default-expanded="true"'), 'default-expanded accordion state is declared');
  assert(html.includes('data-default-collapsed="true"'), 'default-collapsed accordion state is declared for non-default sections');

  const filtersSection = indexOfOrFail(html, 'id="filtersAccordionSection"', 'filters accordion exists');
  const satelliteSection = indexOfOrFail(html, 'id="satelliteAccordionSection"', 'satellite accordion exists');
  const viewSection = indexOfOrFail(html, 'id="viewAccordionSection"', 'view accordion exists');
  const timelinesSection = indexOfOrFail(html, 'id="timelinesAccordionSection"', 'timelines accordion exists');
  const otherSection = indexOfOrFail(html, 'id="otherAccordionSection"', 'other accordion exists');
  const shareSection = indexOfOrFail(html, 'id="shareAccordionSection"', 'share accordion exists');
  const helpSection = indexOfOrFail(html, 'id="helpAccordionSection"', 'help accordion exists');
  assert(!html.includes('id="settingsAccordionSection"'), 'Settings accordion section is removed');
  assert(!html.includes('data-collapsible-target="settingsContent"'), 'Settings content target is removed');
  assert(
    viewSection < satelliteSection && satelliteSection < filtersSection && filtersSection < otherSection &&
      otherSection < timelinesSection && timelinesSection < shareSection && shareSection < helpSection,
    'accordion section order is Views & Time, Satellite Selection, Filters, Other, Timelines, Share, Help'
  );
  assert(html.includes('Views &amp; Time'), 'View section is renamed to Views & Time');

  const viewContent = indexOfOrFail(html, 'id="viewContent"', 'View content exists');
  const menuTimeWarpSlider = indexOfOrFail(html, 'id="menuTimeWarpSlider"', 'menu Time x slider exists');
  const globeToggle = indexOfOrFail(html, 'id="view3DToggle"', 'Globe toggle exists');
  const mercatorToggle = indexOfOrFail(html, 'id="viewMercatorToggle"', 'Mercator toggle exists');
  const starsMilkyWayToggle = indexOfOrFail(html, 'id="starsMilkyWayToggle"', 'Stars & Milky Way toggle exists');
  const highDefToggle = indexOfOrFail(html, 'id="highDefToggle"', 'High Def toggle exists');
  const axesToggle = indexOfOrFail(html, 'id="showECEFAxesToggle"', 'ECEF Axes toggle exists');
  const dayNightToggle = indexOfOrFail(html, 'id="showDayNightToggle"', 'Day/Night toggle exists');
  const starOptions = indexOfOrFail(html, 'id="starsMilkyWayOptions"', 'Stars & Milky Way options container exists');
  const raDecGridToggle = indexOfOrFail(html, 'id="showRaDecGridToggle"', 'RA/Dec Grid toggle exists');
  const brightStarLabelsToggle = indexOfOrFail(html, 'id="showBrightStarLabelsToggle"', 'Bright Labels toggle exists');
  const starAtmosphereToggle = indexOfOrFail(html, 'id="showStarAtmosphereToggle"', 'Atmosphere toggle exists');
  const starMagnitudeSlider = indexOfOrFail(html, 'id="starMagnitudeLimitSlider"', 'Magnitude limit slider exists');
  assert(
    viewContent < menuTimeWarpSlider && menuTimeWarpSlider < globeToggle && globeToggle < mercatorToggle &&
      mercatorToggle < starsMilkyWayToggle && starsMilkyWayToggle < highDefToggle && highDefToggle < axesToggle &&
      axesToggle < dayNightToggle && dayNightToggle < starOptions && starOptions < raDecGridToggle &&
      raDecGridToggle < brightStarLabelsToggle && brightStarLabelsToggle < starAtmosphereToggle &&
      starAtmosphereToggle < starMagnitudeSlider,
    'Views & Time menu order is menu Time x slider, Globe/Mercator/Stars, High Def/ECEF/Day-Night, then star sub-controls'
  );
  assert(!html.includes('Use the time slider at the top of the screen to control simulation speed.'), 'old Views & Time slider guidance is removed');
  assert(html.includes('class="menu-time-warp-control"'), 'Views & Time contains a compact menu time slider control');
  assert(html.includes('for="menuTimeWarpSlider">Time x</label>'), 'menu time slider uses the Time x label');
  assert(html.includes('id="menuTimeWarpVal"'), 'menu time slider has a synchronized value display');
  assert(html.includes('view-control-row view-control-row-three view-primary-row'), 'View menu has a three-item first row');
  assert(html.includes('<label><input type="checkbox" id="starsMilkyWayToggle">Stars &amp; Milky Way</label>'), 'Stars & Milky Way is unchecked by default');
  assert(html.includes('id="starsMilkyWayOptions" class="stars-milky-way-options" hidden aria-hidden="true"'), 'Stars & Milky Way sub-controls are hidden by default');
  assert(html.includes('<label><input type="checkbox" id="showRaDecGridToggle">RA/Dec Grid</label>'), 'RA/Dec Grid is unchecked by default');
  assert(html.includes('<label><input type="checkbox" id="showBrightStarLabelsToggle">Bright Labels</label>'), 'Bright Labels is unchecked by default');
  assert(html.includes('<label><input type="checkbox" id="showStarAtmosphereToggle">Atmosphere</label>'), 'Atmosphere is unchecked by default');
  assert(html.includes('id="starMagnitudeLimitSlider" min="4" max="13" step="0.1" value="10"'), 'Magnitude limit defaults to <10 and caps at <13');
  assert(html.includes('id="starMagnitudeLimitValue">&lt;10.0</span>'), 'Magnitude limit visible value defaults to <10.0');
  assert(html.includes('view-control-row view-control-row-three'), 'View menu keeps a three-item second row');
  assert(!html.includes('view-control-row view-shortcut-row'), 'View menu no longer has a satellite shortcut row');
  assert(html.includes('class="satellite-shortcut-row"'), 'Satellite Selection has a shortcut button row');
  assert(html.includes('aria-label="Starlink shortcut unavailable"'), 'Starlink shortcut has unavailable accessible text before TLE load');
  assert(html.includes('aria-label="ISS shortcut unavailable"'), 'ISS shortcut has unavailable accessible text before TLE load');
  assert(html.includes('Starlink unavailable'), 'Starlink shortcut has required unavailable fallback text');
  assert(html.includes('ISS unavailable'), 'ISS shortcut has required unavailable fallback text');

  assert(indexHtml.includes('DEFAULT_EXPANDED_ACCORDION_SECTIONS = new Set(['), 'required accordion sections are forced open on page load');
  assert(indexHtml.includes('DEFAULT_COLLAPSED_ACCORDION_SECTIONS'), 'other accordion defaults are explicit');
  ['viewContent', 'satelliteSelectionContent', 'filtersContent'].forEach(id => {
    assert(indexHtml.includes(`'${id}'`), `${id} starts expanded on launch`);
  });
  ['otherSelectionsContent', 'timelineContent', 'shareContent', 'helpContent'].forEach(id => {
    assert(indexHtml.includes(`'${id}'`), `${id} starts collapsed on launch`);
  });
  assert(!indexHtml.includes("'settingsContent'"), 'settings content is not part of accordion defaults');
  assert(indexHtml.includes('persisted state cannot reopen') || indexHtml.includes('persisted state cannot override'), 'persisted accordion state cannot override launch defaults');
  assert(indexHtml.includes('setAccordionSectionCollapsed(targetId, nextCollapsed, collapsedSections)'), 'accordion toggles only the targeted section');
  assert(indexHtml.includes('Multiple sections may remain open'), 'implementation documents multi-open accordion behavior');
  assert(indexHtml.includes("expandCollapsibleSection('satelliteSelectionContent')"), 'YPR-enabled selection opens Satellite Selection');
  assert(!indexHtml.includes("expandCollapsibleSection('filtersContent')"), 'YPR selection does not force unrelated sections open');

  assert(!/>\s*Active\s*</i.test(html), 'filter menu does not expose an Active control');
  assert(indexHtml.includes('EXCLUDED_COMPANY_FILTER_OPTIONS'), 'index defines generated company/tag exclusions');
  assert(indexHtml.includes("new Set(['ACTIVE'])"), 'Active is excluded from generated company/tag chips');
  assert(html.includes('id="satelliteSearchInput"'), 'satellite search input is present');
  assert(!html.includes('Select Satellite:'), 'old Select Satellite visible label is removed');
  assert(!html.includes('Search by name, NORAD ID, orbit type, or tag.'), 'old satellite selection helper text is removed');
  assert(html.includes('aria-label="Search satellite by name, NORAD ID, orbit type, or tag"'), 'satellite search keeps an accessible name after visible label removal');
  assert(html.includes('role="combobox"'), 'satellite search uses combobox semantics');
  assert(html.includes('aria-expanded="false"'), 'satellite search exposes collapsed aria-expanded state');
  assert(html.includes('aria-controls="satelliteSearchResults"'), 'satellite search controls the result list');
  assert(html.includes('id="satelliteSearchResults"'), 'satellite search results list is present');
  assert(html.includes('role="listbox"'), 'satellite search results use listbox semantics');
  assert(html.includes('id="satelliteSearchClear"'), 'satellite search clear action is present');
  assert(html.includes('id="resetFiltersButton"'), 'reset filters action is present');
  assert(html.includes('id="filterStatusSummary"'), 'active filter summary is present');
  assert(html.includes('id="filterEmptyState"'), 'filter empty state is present');
  assert(!html.includes('Orbit filter (multi-select):'), 'old orbit filter visible label is removed');
  assert(!html.includes('Choose one or more orbit families. ALL enables every orbit category.'), 'old orbit filter helper text is removed');
  assert(html.includes('id="orbitTypeFilter"'), 'orbit filter controls remain present');
  assert(html.includes('aria-label="Orbit filter"'), 'orbit filter keeps an accessible name');

  const satelliteSelection = indexOfOrFail(html, 'Satellite Selection', 'satellite selection section exists');
  const searchInput = indexOfOrFail(html, 'id="satelliteSearchInput"', 'search input exists');
  const satelliteShortcutRow = indexOfOrFail(html, 'class="satellite-shortcut-row"', 'satellite shortcut row exists');
  const starlinkShortcut = indexOfOrFail(html, 'id="selectFirstStarlinkButton"', 'Starlink shortcut exists');
  const issShortcut = indexOfOrFail(html, 'id="selectIssButton"', 'ISS shortcut exists');
  const selectedControls = indexOfOrFail(html, 'id="selectedSatelliteControls"', 'selected satellite controls exist');
  const firstSatelliteCheckbox = indexOfOrFail(html, 'id="showYPRToggle"', 'satellite-specific checkboxes exist');
  assert(
    satelliteSelection < searchInput && searchInput < satelliteShortcutRow && satelliteShortcutRow < starlinkShortcut &&
      starlinkShortcut < issShortcut && issShortcut < selectedControls && selectedControls < firstSatelliteCheckbox,
    'search/select satellite combo and shortcuts appear between the Satellite Selection header and checkboxes'
  );
  assert(html.includes('id="selectedSatelliteControls" class="satellite-option-grid" aria-label="Selected satellite options" aria-hidden="true" hidden'), 'satellite-specific controls are hidden until selection');
  assert(html.includes('id="showFootprintCheckbox"><span>Show Footprint</span>'), 'Show Footprint checkbox exists and is unchecked by default');
  assert(html.includes('id="showOnlySelectedSatellite" checked'), 'Show only selected satellite checkbox is checked by default when shown');
  assert(html.includes('id="showOrbitFrameToggle"> Orbit Frame (LVLH)'), 'Orbit Frame checkbox exists and is unchecked by default');
  assert(html.includes('id="showOrbitToggle"> Show Orbit'), 'Show Orbit checkbox exists and is unchecked by default');
  assert(!html.includes('No satellite selected'), 'visible no-selection placeholder text is removed from generated menu');
  assert(!html.includes('id="satelliteInfo"'), 'Satellite Selection no longer contains the detailed metadata/TLE table');

  const timelinePanel = indexOfOrFail(html, 'id="timelineContent"', 'timeline content exists');
  const otherPanel = indexOfOrFail(html, 'id="otherSelectionsContent"', 'other content exists');
  const sharePanel = indexOfOrFail(html, 'id="shareContent"', 'share content exists');
  const helpPanel = indexOfOrFail(html, 'id="helpContent"', 'help content exists');
  assert(filtersSection < otherPanel && otherPanel < timelinePanel && timelinePanel < sharePanel && sharePanel < helpPanel, 'Filters follows Satellite Selection and Other/Timelines/Share/Help retain order');
  assert(html.includes('type="checkbox" id="launchTimelineToggle"'), 'launch timeline toggle is a checkbox');
  assert(html.includes('type="checkbox" id="reentryTimelineToggle"'), 're-entry timeline toggle is a checkbox');
  assert(!html.includes('other-selections-heading'), 'Other Selections header does not use a special text-style class');
  assert(html.includes('data-collapsible-target="otherSelectionsContent"'), 'Other Selections is collapsible');
  assert(html.includes('<option value="Mars">Mars</option>'), 'Other Selections includes Mars');
  assert(html.includes('Earth, Moon, and Mars'), 'Other Selections helper mentions Mars');
  assert(html.includes('data-collapsible-target="shareContent"'), 'Share section is collapsible');
  assert(html.includes('data-collapsible-target="helpContent"'), 'Help section is collapsible');
  assert(html.includes('id="menuHeaderRow"'), 'menu header row exists');
  assert(html.indexOf('id="versionDisplay"') < html.indexOf('id="serverStatusBlock"'), 'version appears before server status in header row');
  assert(html.includes('id="serverStatusButton"'), 'server status button exists');
  assert(html.includes('id="serverStatusIcon"'), 'server status uses an icon element');
  assert(html.includes('src="icons/server_checking.svg"'), 'server status starts with checking icon');
  assert(html.includes('aria-label="Checking server connection"'), 'server status has checking accessible text');
  assert(html.includes('id="serverStatusPanel"'), 'server status panel exists');
  assert(html.includes('id="serverReconnectButton"'), 'server status exposes reconnect action');
  assert(!html.includes('Server unavailable. Using local satellite data.'), 'launch offline banner is removed');
  assert(!html.includes('id="serverOfflineNotice"'), 'server offline notice hook is removed');
  assert(html.includes('id="copyShareLinkButton"'), 'Share section includes Copy Link');
  assert(html.includes('id="nativeShareButton"'), 'Share section includes native share action');
  assert(html.includes('id="shareLinkOutput"'), 'Share section includes generated link output');
  assert(html.includes('id="shareImagePreview"'), 'Share section includes canvas image preview');
  assert(html.includes('id="previewShareImageButton"'), 'Share section includes Preview Image action');
  assert(html.includes('id="downloadShareImageButton"'), 'Share section includes Download Image action');
  assert(html.includes('id="copyShareImageButton"'), 'Share section includes Copy Image action');
  assert(html.includes('href="https://github.com/arcazj/openbexi_earth_orbit"'), 'Help includes GitHub project link');
  assert(html.includes('target="_blank" rel="noopener noreferrer"'), 'GitHub Help link opens safely in a new tab');
  assert(html.includes('id="readmeMarkdownLink"'), 'Help includes README Markdown action');
  assert(html.includes('href="markdown_viewer.html?source=README.md&amp;title=README"'), 'README Markdown action opens the Markdown viewer');
  assert(html.includes('id="releasesHistoryMarkdownLink"'), 'Help includes Releases History Markdown action');
  assert(html.includes('href="markdown_viewer.html?source=PROMPT_History.md&amp;title=Releases%20History"'), 'Releases History action opens the Markdown viewer');
  assert(html.includes('>Releases History</strong>'), 'Prompt History action is renamed to Releases History');
  assert(!html.includes('>Prompt History</a>'), 'Prompt History is not the visible Help action text');
  assert(!html.includes('id="helpMarkdownPanel"'), 'Help no longer renders Markdown inline in the menu');
  assert(!html.includes('id="helpMarkdownContent"'), 'Help no longer has an inline Markdown content target');
  assert(html.includes('class="help-smart-grid"'), 'Help uses a smart document grid');
  assert(html.includes('id="licenseMarkdownLink"'), 'Help includes Licenses link hook');
  assert(html.includes('href="LICENSE.md"'), 'Help includes Markdown license link');
  assert(fs.existsSync('LICENSE.md'), 'LICENSE.md exists for the Help license link');
  assert(html.includes('>Licenses</strong>'), 'Help labels the license action as Licenses');
  assert(!html.includes('Swagger / API Documentation'), 'old Swagger/API heading is removed');
  assert(html.includes('Developer Docs'), 'Help includes developer documentation section');
  assert(html.includes('id="swaggerDocsLink"'), 'Help includes Swagger UI link hook');
  assert(html.includes('id="openApiSchemaLink"'), 'Help includes OpenAPI schema link hook');
  assert(html.includes('href="http://127.0.0.1:8000/docs"'), 'Swagger link opens the default docs page');
  assert(html.includes('href="http://127.0.0.1:8000/openapi.json"'), 'API link opens the default OpenAPI page');
  assert(!html.includes('Swagger and OpenAPI documentation are available from the connected Python server.'), 'prohibited Swagger/API sentence is absent from Help markup');
  assert(html.includes('for visualization, educational, and experimental purposes only'), 'Help includes legal disclaimer');
  assert(html.includes('satellite.js'), 'Help disclaimer mentions satellite.js limitations');

  assert(css.includes('.menu-accordion-heading'), 'CSS defines accordion headers');
  assert(css.includes('--menu-metal-yellow'), 'CSS defines a metallic yellow view style');
  assert(css.includes('--menu-metal-blue'), 'CSS defines a metallic blue filters style');
  assert(css.includes('--section-panel-bg'), 'CSS defines section-specific panel backgrounds');
  assert(css.includes('#controlsContainer h3.menu-accordion-heading[aria-expanded="true"]'), 'expanded accordion header contrast rule overrides global h3 color');
  assert(css.includes('color: #06182c !important;'), 'expanded accordion headers use dark high-contrast text');
  assert(css.includes('#controlsContainer h3.menu-accordion-heading[aria-expanded="true"] .toggle-icon'), 'expanded accordion chevron has an explicit readable color');
  assert(!css.includes('.menu-accordion-heading[aria-expanded="true"] {\n    color: #00aaff'), 'expanded accordion headers do not use light blue text');
  assert(css.includes('width: min(380px, calc(100vw - 20px))'), 'menu is thinner than the 1.5.4 accordion menu');
  assert(!css.includes('width: min(420px, calc(100vw - 20px))'), 'previous 420px menu width is no longer used');
  assert(css.includes('#satelliteCountDisplay'), 'satellite count has a dedicated style hook');
  assert(css.includes('color: #ff2a2a !important;'), 'satellite count is styled red');
  assert(css.includes('font-weight: 900;'), 'satellite count is styled bold');
  assert(css.includes('.menu-accordion-section .collapsible-content:not(.collapsed)'), 'long active accordion panels have scroll constraints');
  assert(css.includes('overflow-y: auto'), 'narrowed menu keeps scrollable overflow');
  assert(css.includes('.satellite-search-results'), 'satellite search results have dedicated CSS');
  assert(css.includes('position: fixed'), 'satellite search results can escape accordion clipping');
  assert(css.includes('z-index: 5000'), 'satellite search results render above menu elements');
  assert(css.includes('.satellite-search-results[hidden]'), 'hidden satellite results have an explicit CSS state');
  assert(css.includes('display: none !important;'), 'hidden satellite results are removed from layout');
  assert(css.includes('pointer-events: none !important;'), 'hidden satellite results cannot block controls');
  assert(!css.includes('#satelliteInfo'), 'obsolete Satellite Selection metadata/TLE table CSS is removed');
  assert(css.includes('.selected-satellite-detail-panel'), 'selected satellite detail panel has dedicated CSS');
  assert(css.includes('background: linear-gradient(180deg, rgba(6, 15, 28, 0.74), rgba(3, 8, 16, 0.54))'), 'selected satellite detail panel uses a transparent background');
  assert(css.includes('.selected-satellite-detail-section'), 'selected satellite detail panel has collapsible section CSS');
  assert(css.includes('.selected-satellite-detail-section summary'), 'selected satellite detail panel styles collapsible section toggles');
  assert(css.includes('.selected-satellite-tle-block'), 'selected satellite detail panel styles TLE details');
  assert(css.includes('width: auto;'), 'selected satellite detail panel lets JavaScript sync width to the UTC clock');
  assert(css.includes('#timeWarpBox'), 'time slider has responsive layout CSS');
  assert(css.includes('.menu-time-warp-control'), 'menu Time x slider has dedicated CSS');
  assert(css.includes('#menuTimeWarpSlider'), 'menu Time x slider has dedicated slider CSS');
  assert(css.includes('#mercatorContainer.globe-overlay'), 'Globe + Mercator mode has a dedicated Mercator overlay style');
  assert(css.includes('#mercatorContainer.globe-overlay') && css.includes('bottom: 10px;') && css.includes('right: 10px;'), 'Mercator overlay is anchored to the bottom-right of the globe canvas');
  assert(css.includes('top: 50px !important'), 'narrow viewport time slider is moved away from top controls');
  assert(css.includes('top: 88px'), 'narrow viewport menu starts below the time slider');
  assert(css.includes('.menu-accordion-heading-satellite { border-left-color: #35b9a9; }'), 'Satellite keeps the legacy teal accent');
  assert(css.includes('.menu-accordion-heading-view { border-left-color: #f0b429; }'), 'View keeps the legacy yellow accent');
  assert(css.includes('.menu-accordion-heading-timelines { border-left-color: #d45187; }'), 'Timelines keeps the legacy pink accent');
  assert(css.includes('.menu-accordion-heading-other { border-left-color: #53a7ff; }'), 'Other keeps the legacy blue accent');
  assert(!css.includes('.menu-accordion-heading-other:not([aria-expanded="true"])'), 'Other does not override collapsed header text style');
  assert(!css.includes('.other-selections-heading'), 'Other header special text styling is removed');
  assert(!css.includes('.menu-accordion-heading-settings'), 'Settings accordion accent CSS is removed');
  assert(css.includes('.menu-accordion-heading-share { border-left-color: #6fd08c; }'), 'Share keeps a dedicated legacy-style accent');
  assert(css.includes('.menu-accordion-heading-help { border-left-color: #a98cff; }'), 'Help keeps a dedicated legacy-style accent');
  assert(css.includes('.server-status-button'), 'server status has dedicated CSS');
  assert(css.includes('.menu-header-row'), 'menu top row has dedicated CSS');
  assert(css.includes('--menu-header-control-height: 30px;'), 'menu header controls share a fixed alignment height');
  assert(css.includes('height: var(--menu-header-control-height);'), 'Close and server controls share the header control height');
  assert(css.includes('margin: 0 0 10px 54px;'), 'menu header row reserves aligned space for the external Close button');
  assert(css.includes('.server-status-icon'), 'server status icon has dedicated CSS');
  assert(css.includes('.server-state-connected .server-status-icon'), 'server connected icon state has CSS');
  assert(css.includes('.server-state-disconnected .server-status-icon'), 'server disconnected icon state has CSS');
  assert(css.includes('.server-state-error .server-status-icon'), 'server error icon state has CSS');
  assert(css.includes('.share-panel'), 'Share panel has dedicated CSS');
  assert(css.includes('.share-action-row'), 'Share actions have dedicated CSS');
  assert(css.includes('.share-image-preview-frame'), 'Share image preview has dedicated CSS');
  assert(css.includes('.share-image-action-row'), 'Share image actions have dedicated CSS');
  assert(css.includes('.api-docs-panel'), 'API docs panel has dedicated CSS');
  assert(css.includes('.api-docs-link.is-disabled'), 'API docs disabled state has CSS');
  assert(css.includes('.help-panel'), 'Help panel has dedicated CSS');
  assert(css.includes('.help-smart-grid'), 'Help document grid has dedicated CSS');
  assert(css.includes('.help-doc-card'), 'Help document cards have dedicated CSS');
  assert(!css.includes('.help-markdown-panel'), 'inline Help Markdown preview CSS is removed');
  assert(!css.includes('.help-markdown-content'), 'inline Help Markdown content CSS is removed');
  assert(css.includes('.help-disclaimer'), 'Help disclaimer has dedicated CSS');
  assert(css.includes('.filter-chip input[type="checkbox"]:checked + span'), 'selected tag chips have a distinct active style');
  assert(css.includes(':focus-visible'), 'menu controls have visible focus styling');
  assert(css.includes('@media (max-width: 560px)'), 'menu has narrow viewport behavior');
  assert(css.includes('.view-primary-row'), 'View first row has dedicated Stars & Milky Way CSS');
  assert(css.includes('.view-control-row-three'), 'View rows keep three-column CSS');
  assert(css.includes('.stars-milky-way-options[hidden]'), 'Stars & Milky Way sub-controls are hidden by default through CSS');
  assert(css.includes('.star-magnitude-control'), 'Magnitude limit control has dedicated CSS');
  assert(css.includes('font-size: 13px'), 'Stars & Milky Way controls use readable menu text');
  assert(css.includes('.satellite-shortcut-row'), 'Satellite shortcut row has dedicated CSS');
  assert(css.includes('.satellite-shortcut-button'), 'Satellite shortcut buttons have dedicated CSS');

  assert(indexHtml.includes('MENU_COLLAPSE_STORAGE_KEY'), 'index persists collapsed accordion sections');
  assert(indexHtml.includes('menuTimeWarpSlider'), 'index reads the menu Time x slider');
  assert(indexHtml.includes('menuTimeWarpVal'), 'index reads the menu Time x value');
  assert(indexHtml.includes('sliderValueToTimeWarp'), 'index converts slider values through a shared helper');
  assert(indexHtml.includes('updateTimeWarpControls'), 'index synchronizes both Time x sliders');
  assert(indexHtml.includes('[timeWarpSlider, menuTimeWarpSlider]'), 'canvas and menu Time x sliders share input wiring');
  assert(indexHtml.includes("mercatorContainer.classList.toggle('globe-overlay', show3D)"), 'Mercator overlay class is enabled when Globe and Mercator are both selected');
  assert(indexHtml.includes("mercatorContainer.classList.remove('fullscreen', 'globe-overlay')"), 'Mercator view classes are cleared when Mercator is disabled');
  assert(indexHtml.includes('id="selectedSatelliteDetailPanel"'), 'index defines the selected satellite detail panel');
  assert(indexHtml.includes('updateSelectedSatelliteDetailPanel'), 'index updates the right-side selected satellite detail panel');
  assert(indexHtml.includes('syncSelectedSatelliteDetailPanelWidth'), 'index syncs the selected detail panel width to the UTC clock');
  assert(indexHtml.includes('selectedSatelliteDetailPanel.style.width'), 'selected detail panel width is assigned from the clock measurement');
  assert(indexHtml.includes('SELECTED_DETAIL_DUPLICATE_KEYS'), 'index excludes duplicated selected-detail fields from the metadata table');
  assert(indexHtml.includes("'tle_line1'"), 'TLE line 1 is excluded from duplicate metadata rows');
  assert(indexHtml.includes("'tle_line2'"), 'TLE line 2 is excluded from duplicate metadata rows');
  assert(indexHtml.includes('selected-satellite-tle-block'), 'selected satellite detail panel includes TLE details');
  assert(indexHtml.includes('<details class="selected-satellite-detail-section selected-satellite-data-section" open>'), 'selected satellite data section is expanded by default');
  assert(indexHtml.includes('<details class="selected-satellite-detail-section selected-satellite-tle-section" open>'), 'selected satellite TLE section is expanded by default');
  assert(indexHtml.includes('<span>Satellite data</span>'), 'selected satellite data section has a visible toggle label');
  assert(indexHtml.includes('<span>TLE details</span>'), 'selected satellite TLE section has a visible toggle label');
  assert(indexHtml.includes('Collapse details'), 'satellite data default-open state uses a matching summary hint');
  assert(indexHtml.includes('Collapse TLE'), 'TLE details default-open state uses a matching summary hint');
  assert(indexHtml.includes('selectedSatelliteModelSourceDetail'), 'selected satellite panel computes model source attribution');
  assert(indexHtml.includes('<details class="selected-satellite-detail-section selected-satellite-source-section" open>'), 'selected satellite source detail section is expanded by default');
  assert(indexHtml.includes('<span>Source detail</span>'), 'selected satellite source detail section has a visible toggle label');
  assert(indexHtml.includes('selected-satellite-source-detail'), 'selected satellite source detail text has dedicated styling');
  assert(indexHtml.includes('https://sketchfab.com/malacodart'), 'Starlink model source attribution is present');
  assert(indexHtml.includes('CC Attribution / Creative Commons Attribution'), 'Starlink license attribution is present');
  assert(indexHtml.includes('https://github.com/nasa/NASA-3D-Resources'), 'ISS model source attribution is present');
  assert(indexHtml.includes('NASA (National Aeronautics and Space Administration)'), 'ISS courtesy attribution is present');
  assert(css.includes('.selected-satellite-source-detail'), 'source detail attribution has dedicated CSS');
  assert(css.includes('color: #ff3b30'), 'source detail attribution is red');
  assert(css.includes('font-weight: 800'), 'source detail attribution is bold');
  assert(!indexHtml.includes('updateSatelliteInfo'), 'index no longer updates a menu-side metadata/TLE table');
  assert(!indexHtml.includes('loadHelpMarkdown(source, title)'), 'index no longer renders README and Releases History Markdown inside Help');
  assert(!indexHtml.includes('setupHelpMarkdownLink(readmeMarkdownLink)'), 'README Help action is no longer wired to inline Markdown renderer');
  assert(markdownViewerHtml.includes('renderMarkdown(markdown'), 'Markdown viewer renders Help Markdown in a separate page');
  assert(markdownViewerHtml.includes('escapeHtml(value'), 'Markdown viewer escapes raw HTML');
  assert(markdownViewerHtml.includes('safeMarkdownHref'), 'Markdown viewer sanitizes Markdown links');
  assert(markdownViewerHtml.includes('ALLOWED_MARKDOWN_SOURCES'), 'Markdown viewer restricts allowed source files');
  assert(indexHtml.includes('updateSelectedSatelliteControlsVisibility'), 'index gates selected-satellite controls by selection state');
  assert(indexHtml.includes("'shareContent'"), 'Share starts collapsed with other non-default accordion sections');
  assert(indexHtml.includes("'helpContent'"), 'Help starts collapsed with other non-default accordion sections');
  assert(indexHtml.includes('checkAndLoadServerTleData'), 'index implements server connection and TLE fallback flow');
  assert(indexHtml.includes('tleDataOverride: serverTleData'), 'index passes server TLE data to the existing TLE loader only when available');
  assert(indexHtml.includes('copyCurrentShareLink'), 'index implements Copy Link behavior');
  assert(indexHtml.includes('preserveDrawingBuffer: true'), 'WebGL renderer keeps drawing buffer for Share image capture');
  assert(indexHtml.includes('canvas.toBlob'), 'Share image capture uses canvas.toBlob');
  assert(indexHtml.includes('ClipboardItem'), 'Share image copy checks ClipboardItem support');
  assert(indexHtml.includes('Canvas image capture is unavailable'), 'Share image capture has a fallback message');
  assert(indexHtml.includes('navigator.canShare({ files: [imageFile] })'), 'Native Share includes image only when canShare supports it');
  assert(indexHtml.includes('applyPendingShareStateAfterSatelliteLoad'), 'index restores share state after satellite data loads');
  assert(indexHtml.includes('updateApiDocsState'), 'index updates Swagger/API docs links');
  assert(indexHtml.includes('Swagger and API links still open in a separate page'), 'offline API docs remain clickable with separate-page guidance');
  assert(!indexHtml.includes('Swagger and OpenAPI documentation are available from the connected Python server.'), 'prohibited Swagger/API status sentence is not emitted');
  assert(indexHtml.includes('ensureYPRControlsVisibleForSelection'), 'index preserves YPR controls after satellite selection');
  assert(!/yawSlider\.value\s*=\s*0/.test(indexHtml), 'satellite selection does not reset yaw slider value');
  assert(!/pitchSlider\.value\s*=\s*0/.test(indexHtml), 'satellite selection does not reset pitch slider value');
  assert(!/rollSlider\.value\s*=\s*0/.test(indexHtml), 'satellite selection does not reset roll slider value');
  assert(indexHtml.includes('satelliteSearchText'), 'index implements satellite search matching');
  assert(indexHtml.includes('resetFiltersToDefaults'), 'index implements filter reset');
  assert(indexHtml.includes('setShowOnlySelectedSatellite(true)'), 'selecting a satellite auto-enables show-only-selected mode');
  assert(indexHtml.includes('setShowOnlySelectedSatellite(false)'), 'clearing a satellite disables show-only-selected mode');
  assert(indexHtml.includes('showOnlySelectedSatelliteCheckbox.checked'), 'show-only-selected checkbox is synchronized with simParams');
  assert(indexHtml.includes('enableHighDefForSelectedSatelliteIfNeeded(tleSatData)'), 'non-MEO/GEO selections auto-enable High Def Earth');
  assert(indexHtml.includes("orbitType === 'MEO' || orbitType === 'GEO'"), 'MEO and GEO selections do not force High Def on');
  assert(indexHtml.includes('clearSatelliteSearchInputForNextSelection'), 'search field clears the prior selected label before a new search');
  assert(indexHtml.includes('satelliteSearchClearedForNextSelection'), 'search clearing preserves the current selected satellite');
  assert(indexHtml.includes('findFirstStarlinkSatellite'), 'Satellite Selection shortcut can locate the first Starlink satellite');
  assert(indexHtml.includes('findIssSatellite'), 'Satellite Selection shortcut can locate ISS/ZARYA');
  assert(indexHtml.includes('selectSatelliteViaShortcut'), 'Satellite Selection shortcuts use the normal satellite selection path');
  assert(indexHtml.includes('starlinkShortcutState(findFirstStarlinkSatellite())'), 'Starlink shortcut uses dynamic state helper');
  assert(indexHtml.includes('issShortcutState(findIssSatellite())'), 'ISS shortcut uses dynamic state helper');
  assert(indexHtml.includes("s?.norad_id?.toString() === ISS_NORAD_ID"), 'ISS shortcut prefers NORAD 25544');
  assert(indexHtml.includes('iss-velocity-pitch-nadir-frame'), 'ISS selected model uses pitch-nadir orbital-frame orientation mode');
  assert(indexHtml.includes("const ISS_MODEL_AXIS_MAPPING = 'x-velocity-y-nadir-z-negative-crosstrack'"), 'ISS model maps pitch axis to nadir');
  assert(indexHtml.includes('ISS_MODEL_EARTH_FACING_AXIS = { x: 0, y: 1, z: 0 }'), 'ISS fallback nadir orientation uses pitch axis as Earth-facing');
  assert(indexHtml.includes('+Y pitch/nadir toward Earth'), 'ISS diagnostics document pitch axis pointing toward Earth');
  assert(indexHtml.includes('pitchAxisEarthFacing = true'), 'ISS diagnostics mark pitch as Earth-facing');
  assert(indexHtml.includes('calibrationPitchDeg'), 'ISS orientation diagnostics include pitch calibration');
  assert(indexHtml.includes('calibrationRollDeg'), 'ISS orientation diagnostics include roll calibration');
  assert(indexHtml.includes('selectedSatelliteOrientationBias(isIssModel)'), 'selected model orientation uses a model-specific control-bias helper');
  assert(indexHtml.includes("controlMapping: isIssModel ? 'iss-yaw-pitch-swapped'"), 'ISS selected model swaps yaw and pitch control mapping');
  assert(indexHtml.includes('yawDeg: isIssModel ? simParams.pitchDeg : simParams.yawDeg'), 'ISS yaw input uses the pitch slider value');
  assert(indexHtml.includes('pitchDeg: isIssModel ? simParams.yawDeg : simParams.pitchDeg'), 'ISS pitch input uses the yaw slider value');
  assert(indexHtml.includes('rollDeg: simParams.rollDeg'), 'ISS roll input remains unchanged');
  assert(indexHtml.includes('detailedSatelliteModel.userData.appliedYawDeg = orientationBias.yawDeg'), 'ISS diagnostics expose applied yaw after swap');
  assert(indexHtml.includes('detailedSatelliteModel.userData.appliedPitchDeg = orientationBias.pitchDeg'), 'ISS diagnostics expose applied pitch after swap');
  assert(indexHtml.includes('visible = !!currentSelectedSatellite'), 'show-only visibility is not constrained by current filters');
  assert(indexHtml.includes('earthInView: selectedCameraFrameKeepsEarthInView'), 'selected-satellite camera metadata checks Earth remains visible');
  assert(indexHtml.includes('function computeSelectedModelObserverFrame'), 'selected detailed model uses a reusable observer-frame calculation');
  assert(indexHtml.includes('selectedStarlinkCameraFrameOptions(targetPos, propagation)'), 'Starlink camera frame is recomputed from current propagation');
  assert(indexHtml.includes('updateSelectedModelTracking(selectedPropagation)'), 'selected model tracking receives the current propagation state');
  assert(indexHtml.includes('selectedModelTracking.localCameraOffset'), 'selected model tracking preserves user zoom/orbit offset');
  assert(indexHtml.includes('selectedFrameLocalToCameraOffset'), 'selected model tracking reapplies user camera offset in the current observer frame');
  assert(indexHtml.includes('cameraMove.endCamPos.copy(trackingFrame.cameraPosition)'), 'selected model fly-to target follows the recomputed observer frame during time changes');
  assert(indexHtml.includes('SELECTED_ORBIT_ALIGNMENT_TOLERANCE_SCENE_UNITS = 0.01'), 'selected model orbit alignment tolerance is explicit');
  assert(indexHtml.includes('orbitAlignmentDebugEnabled'), 'selected model orbit alignment debug mode exists');
  assert(indexHtml.includes('function setDetailedSatelliteModelPositionFromPropagation'), 'selected model root position uses a canonical propagation helper');
  assert(indexHtml.includes('selectedOrbitNearestPointDistance(modelWorldPosition)'), 'selected model diagnostics measure distance to selected orbit line');
  assert(indexHtml.includes('currentSelectedSatellite.mesh.position.copy(propagatedScenePosition)'), 'hidden selected sprite is synchronized with the detailed model root');
  assert(indexHtml.includes('rootToPropagatedDistanceSceneUnits'), 'selected model diagnostics report root-to-propagated distance');
  assert(!indexHtml.includes('eciToSceneVector(detailedSatelliteModel.position'), 'selected model root position is not written outside the canonical helper');
  assert(indexHtml.includes('const EARTH_SURFACE_MIN_ZOOM_KM = 100'), 'Earth-mode minimum zoom is defined as 100 km above surface');
  assert(indexHtml.includes('const EARTH_MODE_MIN_DISTANCE = EARTH_SCENE_RADIUS + EARTH_SURFACE_MIN_ZOOM_KM * KM_TO_SCENE_UNITS'), 'Earth min zoom is Earth radius plus 100 km, not distance from center');
  assert(indexHtml.includes('const SAFE_MAX_CONTROL_DISTANCE = EARTH_SCENE_RADIUS * 100000'), 'maximum zoom is very large and finite');
  assert(indexHtml.includes('const SAFE_CAMERA_FAR = Math.max'), 'camera far plane has a safe finite bound');
  assert(indexHtml.includes('controls.enablePan = false'), 'OrbitControls panning is disabled so target cannot drift');
  assert(indexHtml.includes('function enforceSceneOrigin()'), 'index enforces Earth scene origin');
  assert(indexHtml.includes('earthMesh.position.set(0, 0, 0)'), 'Earth mesh is pinned at scene origin');
  assert(indexHtml.includes('function enforceActiveControlTarget()'), 'index defines active camera target priority enforcement');
  assert(indexHtml.includes('controls.target.copy(moon.position)'), 'Moon mode targets the Moon position');
  assert(indexHtml.includes('controls.target.copy(mars.position)'), 'Mars mode targets the Mars position');
  assert(indexHtml.includes("import { createMars, updateMars } from './js/MarsFrameLoader.js';"), 'index imports Mars frame helpers');
  assert(indexHtml.includes("textureUrl: 'textures/March.jpg'"), 'index creates Mars with the required local texture');
  assert(indexHtml.includes('id="marsTextureLoading"'), 'index includes a Mars texture loading status panel');
  assert(indexHtml.includes('Loading Mars map/texture...'), 'Mars texture loading panel has the required label');
  assert(indexHtml.includes('onTextureLoadProgress: handleMarsTextureProgress'), 'index wires Mars texture progress callbacks');
  assert(indexHtml.includes("onTextureLoadStart: () => recordMarsTextureLoadState('loading', 0)"), 'Mars startup texture load records state without directly showing the progress panel');
  assert(!indexHtml.includes("onTextureLoadStart: () => setMarsTextureLoadingState('loading', 0)"), 'Mars startup texture load does not directly show the progress panel');
  assert(indexHtml.includes('function shouldShowMarsTextureProgress()'), 'index gates visible Mars texture progress by active context');
  assert(indexHtml.includes("return simParams.otherSelection === 'Mars'"), 'Mars texture progress is visible only when Mars is active');
  assert(indexHtml.includes('showMarsTextureProgressForSelection()'), 'selecting Mars explicitly shows the centered progress panel');
  assert(indexHtml.includes('hideMarsTextureLoadingPanel()'), 'leaving Mars hides the Mars progress panel');
  assert(indexHtml.includes("if (!shouldShowMarsTextureProgress()) return;"), 'Mars Mercator progress events are ignored unless Mars is active');
  assert(indexHtml.includes('MARS_TEXTURE_LOADING_MIN_VISIBLE_MS = 1600'), 'Mars texture loading panel stays visible long enough for cached/local loads');
  assert(indexHtml.includes("window.addEventListener('openbexi:mars-map-loading'"), 'index listens for Mars Mercator map loading progress');
  assert(indexHtml.includes('Mars texture failed to load. Using fallback Mars color.'), 'Mars texture load failure has a visible fallback message');
  assert(indexHtml.includes('MARS_CAMERA_DISTANCE_MULTIPLIER = 1.45'), 'Mars observer starts close to the Mars globe');
  assert(indexHtml.includes('distanceMultiplier: simParams.otherSelection === \'Mars\' ? MARS_CAMERA_DISTANCE_MULTIPLIER : 4'), 'Mars selection uses the closer observer distance');
  assert(indexHtml.includes('mercatorUsesEarthSatellites = simParams.otherSelection !== \'Mars\''), 'Mercator suppresses Earth satellite overlays in Mars context');
  assert(indexHtml.includes("simParams.otherSelection === 'Mars'"), 'index handles Mars in Other Selections');
  assert(indexHtml.includes('if (mars) updateMars(mars, SIM_DATE)'), 'index updates Mars each frame');
  assert(indexHtml.includes('updateMars(mars, SIM_DATE);'), 'index initializes Mars position before the first selectable frame');
  assert(indexHtml.includes("import { BRIGHT_STARS_DEMO } from './data/stars/bright-stars-demo.js';"), 'index imports the real RA/Dec demo star catalog');
  assert(indexHtml.includes('MAX_INTEGRATED_STAR_MAGNITUDE_LIMIT'), 'index imports the integrated magnitude limit cap');
  assert(indexHtml.includes('showStarsMilkyWay: false'), 'Stars & Milky Way is disabled by default in simParams');
  assert(indexHtml.includes('showRaDecGrid: false'), 'RA/Dec Grid is disabled by default in simParams');
  assert(indexHtml.includes('showBrightStarLabels: false'), 'Bright Labels is disabled by default in simParams');
  assert(indexHtml.includes('showStarAtmosphere: false'), 'Atmosphere is disabled by default in simParams');
  assert(indexHtml.includes('starMagnitudeLimit: DEFAULT_STAR_MAGNITUDE_LIMIT'), 'main app star magnitude limit defaults to <10');
  assert(indexHtml.includes('const MILKY_WAY_TEXTURE_URL = \'obj/Textures/starmap-4k.jpg\''), 'main app uses the local Milky Way texture path');
  assert(indexHtml.includes('function initStarsMilkyWayLayer()'), 'index initializes the optional Stars & Milky Way layer');
  assert(indexHtml.includes('new THREE.Points(geometry, starMaterial)'), 'Stars are rendered as a single THREE.Points layer');
  assert(indexHtml.includes('new THREE.SphereGeometry(STAR_SKY_RADIUS * 1.02'), 'Milky Way renders as a celestial sphere');
  assert(indexHtml.includes('buildStarBufferData(BRIGHT_STARS_DEMO'), 'star field uses the real RA/Dec demo catalog');
  assert(indexHtml.includes('function syncStarsMilkyWayControlsVisibility()'), 'index hides/shows star sub-controls');
  assert(indexHtml.includes('starsMilkyWayOptionsElement.hidden = !visible'), 'star sub-controls are hidden when Stars & Milky Way is off');
  assert(indexHtml.includes('starMagnitudeLimitSliderElement?.addEventListener(\'input\''), 'magnitude limit updates the star field without app reload');
  assert(indexHtml.includes('MAX_INTEGRATED_STAR_MAGNITUDE_LIMIT'), 'magnitude limit is capped for the integrated main view');
  assert(indexHtml.includes('milkyWaySphere.visible = showSky'), 'Milky Way is visible only when Stars & Milky Way is enabled');
  assert(indexHtml.includes('starPoints.visible = showSky'), 'Star points are visible only when Stars & Milky Way is enabled');
  assert(indexHtml.includes('raDecGrid.visible = showSky && !!simParams.showRaDecGrid'), 'RA/Dec grid depends on Stars & Milky Way and its checkbox');
  assert(indexHtml.includes('brightStarLabelGroup.visible = showSky && !!simParams.showBrightStarLabels'), 'Bright labels depend on Stars & Milky Way and its checkbox');
  assert(indexHtml.includes('starAtmosphereMesh.visible = showSky && !!simParams.showStarAtmosphere'), 'Atmosphere depends on Stars & Milky Way and its checkbox');
  assert(indexHtml.includes('controls.target.set(0, 0, 0)'), 'Earth mode targets the Earth center');
  assert(!indexHtml.includes('moon.position.set(0, 0, 0)'), 'Moon mode does not move the Moon object to scene origin');
  assert(!indexHtml.includes('mars.position.set(0, 0, 0)'), 'Mars mode does not move the Mars object to scene origin');
  assert(marsFrameLoader.includes('onTextureLoadStart'), 'Mars loader exposes a texture load start callback');
  assert(marsFrameLoader.includes('onTextureLoadProgress'), 'Mars loader exposes texture progress callbacks');
  assert(marsFrameLoader.includes('onTextureLoadComplete'), 'Mars loader exposes texture complete callbacks');
  assert(marsFrameLoader.includes('onTextureLoadError'), 'Mars loader exposes texture error callbacks');
  assert(mercatorMapLoader.includes("import {MARS_TEXTURE_URL} from './MarsFrameLoader.js';"), 'Mercator loader imports the Mars texture path');
  assert(mercatorMapLoader.includes('mercatorBackgroundUrlForContext'), 'Mercator loader resolves background texture from active context');
  assert(mercatorMapLoader.includes("simParams?.otherSelection === 'Mars'"), 'Mercator loader detects Mars context');
  assert(mercatorMapLoader.includes('Mars Mercator map'), 'Mercator loader labels the Mars map context');
  assert(mercatorMapLoader.includes('return isMarsMercatorContext(simParams) ? MARS_TEXTURE_URL : earthConfig.textureLight'), 'Mercator loader uses Mars texture instead of Earth texture in Mars context');
  assert(mercatorMapLoader.includes("CustomEvent('openbexi:mars-map-loading'"), 'Mercator loader emits Mars map loading events');
  assert(css.includes('.planet-texture-loading'), 'CSS styles the Mars texture loading progress panel');
  assert(css.includes('left: 50%;') && css.includes('top: 50%;') && css.includes('transform: translate(-50%, -50%)'), 'Mars texture loading progress panel is centered on the canvas');
  assert(css.includes('.planet-texture-progress-fill'), 'CSS styles the Mars texture loading progress fill');
  assert(css.includes('.mapBackground[data-map-body="Mars"].fallback-css'), 'CSS provides a Mars-specific Mercator fallback texture state');
  assert(indexHtml.includes('if (currentSelectedSatellite || detailedSatelliteModel?.visible) return;'), 'selected satellite target priority is preserved over Earth/Moon target enforcement');
  assert(indexHtml.includes('camera.far = SAFE_CAMERA_FAR'), 'camera far plane is restored to the safe finite bound');
  assert(indexHtml.includes('isSatelliteDropdownOpen'), 'satellite search uses explicit dropdown open state');
  assert(indexHtml.includes('positionSatelliteSearchResults'), 'satellite search results are positioned over menu elements');
  assert(indexHtml.includes('document.body.appendChild(satelliteSearchResults)'), 'satellite search results are portaled outside accordion clipping');
  assert(indexHtml.includes('insideResults = satelliteSearchResults?.contains(event.target)'), 'outside-click handling preserves clicks inside portaled results');
  assert(indexHtml.includes('document.addEventListener(\'pointerdown\''), 'outside clicks close satellite search results');
  assert(indexHtml.includes("event.key === 'Tab'"), 'Tab closes satellite search results without trapping focus');
  assert(indexHtml.includes('if (forceOpen) isSatelliteDropdownOpen = true'), 'only explicit user actions open satellite search results');
  assert(indexHtml.includes('aria-activedescendant'), 'satellite search supports active descendant keyboard state');
  assert(indexHtml.includes('syncExclusiveTimelineSelection'), 'index enforces mutually exclusive timeline checkboxes');
  assert(indexHtml.includes("hideTimelineById('reentryTimelineToggle')"), 'launch selection hides re-entry timeline');
  assert(indexHtml.includes("hideTimelineById('launchTimelineToggle')"), 're-entry selection hides launch timeline');
  assert(indexHtml.includes('handle.setVisible(false)'), 'timeline exclusivity hides the inactive HUD through timeline handles');
  assert(launchTimeline.includes("toggle?.type === 'checkbox'"), 'launch timeline supports checkbox toggles');
  assert(reentryTimeline.includes("toggle?.type === 'checkbox'"), 're-entry timeline supports checkbox toggles');
  assert(launchTimeline.includes('setVisible: setVisibility'), 'launch timeline exposes explicit visibility control');
  assert(reentryTimeline.includes('setVisible: setVisibility'), 're-entry timeline exposes explicit visibility control');
  assert(launchTimeline.includes('isVisible()'), 'launch timeline exposes visibility state');
  assert(reentryTimeline.includes('isVisible()'), 're-entry timeline exposes visibility state');

  console.log('menuUx tests passed');
}

run();
