import fs from 'node:fs';

const record = JSON.parse(fs.readFileSync('release/version.json', 'utf8'));
const featureRegistry = JSON.parse(fs.readFileSync('release/feature-flags.json', 'utf8'));
const properties = Object.entries(record)
  .map(([key, value]) => `  ${key}: ${JSON.stringify(value)}`)
  .join(',\n');
const browserFlags = Object.fromEntries((featureRegistry.flags ?? [])
  .filter(flag => flag.scope === 'browser')
  .map(flag => [
  flag.id,
  {
    enabled: flag.enabled === true &&
      Array.isArray(flag.enabledChannels) &&
      flag.enabledChannels.includes(record.channel) &&
      String(flag.scientificMaturity).toLowerCase() === record.maturity &&
      flag.safetyClass === record.safetyClass,
    scope: String(flag.scope ?? ''),
    scientificMaturity: String(flag.scientificMaturity ?? ''),
    safetyClass: String(flag.safetyClass ?? '')
  }
]));
const flagProperties = Object.entries(browserFlags)
  .map(([id, flag]) => `  ${JSON.stringify(id)}: Object.freeze(${JSON.stringify(flag)})`)
  .join(',\n');
const output = `// Generated by \`npm run version:sync\` from release/version.json and release/feature-flags.json. Do not edit.\n` +
  `export const RELEASE_METADATA = Object.freeze({\n${properties}\n});\n\n` +
  `export const APP_VERSION = RELEASE_METADATA.version;\n` +
  `export const RELEASE_DATE = RELEASE_METADATA.releasedAt ?? RELEASE_METADATA.candidateAt;\n\n` +
  `export const RELEASE_FEATURE_FLAGS = Object.freeze({\n${flagProperties}\n});\n` +
  `export const EXPERIMENTAL_CONJUNCTION_SCREENING_ENABLED =\n` +
  `  RELEASE_FEATURE_FLAGS.experimental_conjunction_screening?.enabled === true;\n`;

fs.writeFileSync('js/releaseVersion.js', output, 'utf8');
console.log(`Synchronized browser release metadata for ${record.version}.`);
